; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Project uses release notes, you must set FAMISTUDIO_USE_RELEASE_NOTES = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; DPCM Delta Counter effect is used, you must set FAMISTUDIO_USE_DELTA_COUNTER = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_chapter_complete=music_data_chapter_complete
.endif

music_data_chapter_complete:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : chapter_complete
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_chapter_complete
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env3,@env1,@env0 ; 00 : piano

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c2,$c1,$00,$01
@env2:
	.byte $05,$cb,$cc,$00,$02,$ca,$c8,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c0,$00,$0f
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $7f,$00,$00

@samples:

@song0ch0:
	.byte $51, $ff, $e0, $80, $16, $8d, $7f, $51, $ff, $e0, $1d, $8d, $7f, $51, $ff, $e0, $22, $8d, $7f, $51, $ff, $e0, $29, $8d
	.byte $7f, $51, $ff, $e0, $2e, $89, $45, $81, $7f, $51, $fe, $e0, $11, $81, $7f, $51, $ff, $e0, $15, $81, $7f, $51, $ff, $e0
	.byte $1f, $95, $7f, $51, $fe, $e0, $0c, $81, $7f, $51, $ff, $e0, $16, $81, $7f, $51, $ff, $e0, $21, $95, $7f, $51, $fd, $e0
	.byte $0a, $81, $7f, $51, $ff, $e0, $18, $81, $7f, $1d, $85, $51, $fc, $00, $8f, $81
@song0ch0loop:
	.byte $00, $fd, $42
	.word @song0ch0loop
@song0ch1:
	.byte $87, $51, $ff, $e0, $80, $1b, $8d, $7f, $51, $ff, $e0, $21, $8d, $7f, $51, $ff, $e0, $27, $8d, $7f, $51, $ff, $e0, $2d
	.byte $8d, $7f, $51, $ff, $e0, $33, $81, $45, $81, $81, $7f, $51, $ff, $e0, $13, $81, $7f, $51, $ff, $e0, $16, $99, $7f, $51
	.byte $ff, $e0, $13, $81, $7f, $51, $ff, $e0, $1b, $99, $7f, $51, $ff, $e0, $11, $81, $7f, $1a, $87, $51, $fc, $00, $91
@song0ch1loop:
	.byte $70, $00, $fd, $42
	.word @song0ch1loop
@song0ch2:
	.byte $51, $ff, $e0, $80, $22, $85, $7f, $51, $ff, $e0, $27, $85, $7f, $51, $ff, $e0, $29, $85, $7f, $51, $ff, $e0, $2d, $85
	.byte $7f, $51, $ff, $e0, $2e, $85, $7f, $51, $ff, $e0, $33, $85, $7f, $51, $ff, $e0, $35, $85, $7f, $51, $ff, $e0, $39, $85
	.byte $7f, $51, $ff, $e0, $3a, $85, $7f, $51, $ff, $e0, $3f, $81, $45, $81, $89, $7f, $51, $ff, $e0, $3a, $9d, $7f, $51, $ff
	.byte $e0, $3a, $83, $7f, $51, $ff, $e0, $35, $85, $7f, $51, $ff, $e0, $3c, $85, $45, $87, $7f, $51, $fe, $00, $3e, $87, $45
	.byte $8b
@song0ch2loop:
	.byte $70, $00, $fd, $42
	.word @song0ch2loop
@song0ch3:
	.byte $46, $08, $46, $08, $8f, $46, $06, $a7, $46, $05, $97, $46, $04, $89, $46, $0d, $95, $46, $04, $89, $46, $0f, $95, $46
	.byte $03, $89, $46, $0f, $97
@song0ch3loop:
	.byte $ff, $42
	.word @song0ch3loop
@song0ch4:
	.byte $52, $d0, $cf, $52, $d0, $e1
@song0ch4loop:
	.byte $ff, $42
	.word @song0ch4loop
