; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_ch3=music_data_ch3
.endif

music_data_ch3:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : clutter_0
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : finalboss
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_ch3
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env9,@env6,@env11,@env0 ; 00 : Maracas
	.word @env10,@env6,@env11,@env0 ; 01 : Low Floor Tom
	.word @env2,@env6,@env11,@env0 ; 02 : Snare
	.word @env14,@env6,@env11,@env0 ; 03 : Snare_
	.word @env3,@env6,@env12,@env0 ; 04 : Piano
	.word @env1,@env6,@env12,@env0 ; 05 : Piano Long
	.word @env4,@env6,@env12,@env8 ; 06 : Whistle
	.word @env7,@env6,@env12,@env0 ; 07 : Piano XL
	.word @env15,@env6,@env11,@env0 ; 08 : Harpsichord
	.word @env5,@env6,@env13,@env0 ; 09 : Bass

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$ca,$cc,$cd,$ce,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c6,$c5,$c4,$c2,$c2,$c1,$c0,$00,$13
@env2:
	.byte $00,$cf,$cc,$ca,$c7,$c4,$c1,$c0,$00,$07
@env3:
	.byte $00,$cc,$cf,$cf,$ce,$cd,$cc,$ca,$c8,$c5,$c0,$00,$0a
@env4:
	.byte $00,$c3,$c7,$ca,$cd,$cf,$cf,$ce,$cc,$c9,$00,$09
@env5:
	.byte $00,$c2,$c6,$c8,$ca,$02,$c8,$c6,$c2,$00,$08
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$c4,$c6,$c8,$c8,$c9,$02,$c8,$c7,$c6,$02,$c5,$0b,$c4,$06,$c3,$03,$c2,$c1,$00,$12
@env8:
	.byte $00,$c1,$c3,$c7,$c9,$c8,$c6,$c2,$c0,$00,$08
@env9:
	.byte $00,$cf,$c6,$00,$02
@env10:
	.byte $00,$cf,$c0,$00,$02
@env11:
	.byte $7f,$00,$00
@env12:
	.byte $c2,$7f,$00,$00
@env13:
	.byte $c1,$7f,$00,$00
@env14:
	.byte $00,$c6,$ca,$cf,$cf,$ce,$cb,$c8,$c4,$c1,$c0,$00,$0a
@env15:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$c9,$c7,$c4,$c1,$00,$09

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $00, $91, $88
@song0ref8:
	.byte $2e, $8f, $30, $8f, $31, $8f, $8a, $29, $a1, $2e, $a1, $00, $91, $88, $2e, $8f, $30, $8f, $31, $8f, $8a, $27, $a1, $24
	.byte $a1, $48
	.byte $41, $14
	.word @song0ref5
	.byte $27, $8f, $25, $8f, $24, $8f, $29, $8f, $48, $00, $91
	.byte $41, $16
	.word @song0ref8
	.byte $48
	.byte $41, $14
	.word @song0ref5
	.byte $27, $8f, $25, $8f, $24, $8f, $29, $8f, $48, $00, $91, $2a, $8f, $2c, $8f, $2e, $8f, $8a, $25, $a1, $2a, $a1, $00, $91
	.byte $88, $2a, $8f, $2c, $8f, $2e, $8f, $27, $8f, $25, $8f, $24, $8f, $29, $8f, $48, $00, $91, $29, $8f, $2c, $8f, $30, $8f
	.byte $8a, $24, $a1, $29, $a1, $00, $91, $88, $24, $8f, $29, $8f, $2c, $8f, $00, $8f, $24, $8f, $28, $8f, $2b
@song0ref124:
	.byte $8f, $48, $00, $91
@song0ref128:
	.byte $29, $8f, $2b, $8f, $2c, $8f, $8a, $24, $a1, $29, $a1, $00, $91, $88, $29, $8f, $2b, $8f, $2c, $8f, $8a, $22, $a1, $1f
	.byte $a1, $48, $00, $91, $88
	.byte $41, $12
	.word @song0ref128
	.byte $22, $8f, $20, $8f, $1f, $8f, $24
	.byte $41, $1b
	.word @song0ref124
	.byte $88
	.byte $41, $12
	.word @song0ref128
	.byte $22, $8f, $20, $8f, $1f, $8f, $24, $8f, $48, $00, $91, $25, $8f, $27, $8f, $29, $8f, $8a, $22, $a1, $25, $a1, $00, $91
	.byte $88, $25, $8f, $27, $8f, $29, $8f, $22, $8f, $20, $8f, $1f, $8f, $24, $8f, $48, $00, $91, $24, $8f, $27, $8f, $2b, $8f
	.byte $8a, $1f, $a1, $24, $a1, $00, $91, $88, $1f, $8f, $24, $8f, $27, $8f, $00, $8f, $1f, $8f, $00, $8f, $26, $8f, $48, $00
	.byte $ff, $ff, $a1, $48, $ff, $ff, $a3, $48, $ff, $ff, $a3, $48, $ff, $ff, $a3, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $8e
@song0ref266:
	.byte $16, $ff, $8f, $12, $ff, $8f, $16, $ff, $8f, $12, $ff, $8f
	.byte $41, $0c
	.word @song0ref266
	.byte $12, $ff, $8f, $0f, $ff, $8f, $11, $ff, $8f, $05, $c7, $0c, $c5
@song0ref294:
	.byte $11, $ff, $8f, $0d, $ff, $8f, $11, $ff, $8f, $0d, $ff, $8f
	.byte $41, $0c
	.word @song0ref294
	.byte $0d, $ff, $8f, $0a, $ff, $8f, $0c, $ff, $8f, $40, $0c, $91, $00, $b3, $07, $8f, $00, $b3
@song0ref327:
	.byte $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $0c
	.word @song0ref327
	.byte $41, $0c
	.word @song0ref327
	.byte $41, $0c
	.word @song0ref327
	.byte $41, $0c
	.word @song0ref327
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref360:
	.byte $40, $4e, $81, $00, $9f, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $9d, $40, $4e, $81, $00
	.byte $8b, $40, $4e, $81, $00, $8b
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $18
	.word @song0ref360
	.byte $41, $0c
	.word @song0ref327
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0c
	.word @song0ref327
	.byte $41, $0c
	.word @song0ref327
	.byte $41, $0c
	.word @song0ref327
	.byte $41, $0c
	.word @song0ref327
	.byte $42
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $90
@song1ref6:
	.byte $2e, $b5, $30, $8f, $31, $8f, $00, $8f, $36, $8f, $00, $8f, $2d, $91, $00, $8f, $35, $8f, $33, $8f, $31, $8f, $00, $8f
	.byte $2a, $8f, $2e, $8f, $48, $2d
@song1ref36:
	.byte $91, $00, $8f, $30, $8f, $31, $8f, $33, $8f, $00, $8f, $30, $8f, $00, $8f, $31, $91, $00, $8f, $35, $8f, $33, $8f, $31
	.byte $8f, $30, $8f, $2e, $8f, $2d, $8f, $48, $2a, $91, $00, $8f, $30, $8f, $31, $8f, $33, $8f, $00, $8f, $30, $8f, $00, $8f
	.byte $31, $91, $00, $8f, $2e, $8f, $2d, $8f, $2e, $8f, $00, $8f, $30, $8f, $31, $8f, $48, $33, $91, $35, $8f, $36, $8f, $2d
	.byte $8f, $31, $8f, $33, $8f, $35, $8f, $2e, $8f, $30, $91, $31, $8f, $33, $8f, $36, $8f, $35, $8f, $34, $8f, $35, $8f, $00
	.byte $8f, $48
	.byte $41, $1c
	.word @song1ref6
	.byte $48, $30
	.byte $41, $5f
	.word @song1ref36
	.byte $48
	.byte $41, $7c
	.word @song1ref6
	.byte $48
	.byte $41, $1c
	.word @song1ref6
	.byte $48, $30
	.byte $41, $5f
	.word @song1ref36
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $8c, $40, $01, $81, $00, $ff, $ff, $9d, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3
@song1ref176:
	.byte $22, $c7, $24, $c5, $25, $c7, $2a, $c5, $21, $c7, $29, $a1, $27, $a1, $25, $c7, $22, $c5, $1e, $c7, $27, $a1, $25, $a1
	.byte $24, $c7, $1e, $c5, $1d, $c7, $29, $a1, $27, $a1, $25, $c7, $22, $a1, $21, $a1
	.byte $41, $28
	.word @song1ref176
	.byte $41, $28
	.word @song1ref176
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $8c, $40, $01, $81, $00, $ff, $ff, $9d
@song1ref234:
	.byte $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $92
@song1ref256:
	.byte $16, $ff, $8f, $00, $c7, $22, $c5, $15, $ff, $8f, $00, $c7, $21, $a1, $2d, $a1, $12, $ff, $8f, $00, $c7, $1e, $c5, $11
	.byte $ff, $8f, $00, $c7, $1d, $a1, $29, $a1
	.byte $41, $20
	.word @song1ref256
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref295:
	.byte $83, $82, $24, $8d, $80, $40, $4e, $81, $00, $8b, $40, $4e, $81, $82, $24, $8b, $80, $40, $4e, $81, $00, $8f, $84, $31
	.byte $87, $86, $31, $81, $80, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $9f, $40, $4e, $81, $00
	.byte $8b, $40, $4e, $81, $82, $24, $8b, $80, $40, $4e, $81, $00, $8f, $84, $31, $87, $86, $31, $81, $80, $40, $4e, $81, $82
	.byte $24, $8b, $80, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $41, $3b
	.word @song1ref295
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $41, $15
	.word @song1ref234
	.byte $41, $15
	.word @song1ref234
	.byte $ff, $ff, $a3, $ff, $ff, $a3, $42
	.word @song1ch4loop
