; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_ch1=music_data_ch1
.endif

music_data_ch1:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : MUS - first steps
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_ch1
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env10,@env16,@env0 ; 00 : DPCM
	.word @env33,@env34,@env16,@env0 ; 01 : N hat
	.word @env5,@env7,@env21,@env0 ; 02 : N kick
	.word @env6,@env10,@env17,@env0 ; 03 : decending
	.word @env8,@env19,@env16,@env0 ; 04 : triangle
	.word @env3,@env2,@env31,@env0 ; 05 : N snare
	.word @env32,@env10,@env17,@env0 ; 06 : pad
	.word @env8,@env11,@env20,@env0 ; 07 : flute
	.word @env1,@env10,@env17,@env0 ; 08 : soft piano

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ce,$cd,$c7,$cb,$ca,$c9,$c5,$c8,$c7,$c7,$c4,$c6,$c6,$c5,$c3,$c4,$c3,$c3,$c2,$00,$11
@env2:
	.byte $c8,$c2,$c1,$c0,$c8,$00,$04
@env3:
	.byte $00,$cf,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c6,$02,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$15
@env4:
	.byte $00,$c0,$be,$be,$c0,$c2,$c2,$00,$01
@env5:
	.byte $00,$c9,$cf,$cf,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c2,$c1,$00,$0c
@env6:
	.byte $00,$c5,$c9,$ce,$c2,$00,$04
@env7:
	.byte $cb,$c0,$c0,$cb,$00,$03
@env8:
	.byte $00,$cf,$7f,$00,$02
@env9:
	.byte $00,$c0,$bf,$bf,$be,$02,$bf,$bf,$c0,$c1,$c1,$c2,$02,$c1,$c1,$00,$01
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $bf,$c0,$00,$01
@env12:
	.byte $c0,$cc,$c5,$00,$00
@env13:
	.byte $c0,$cc,$c4,$00,$00
@env14:
	.byte $00,$c0,$c0,$bf,$04,$c0,$02,$c1,$04,$c0,$00,$01
@env15:
	.byte $00,$c0,$be,$bd,$bd,$bf,$c1,$c3,$c3,$c2,$00,$01
@env16:
	.byte $7f,$00,$00
@env17:
	.byte $c2,$7f,$00,$00
@env18:
	.byte $00,$c0,$c0,$bf,$02,$be,$06,$bf,$02,$c0,$02,$c1,$02,$c2,$06,$c1,$02,$c0,$00,$01
@env19:
	.byte $e7,$e4,$e2,$dc,$d9,$d6,$d5,$00,$06
@env20:
	.byte $c1,$7f,$00,$00
@env21:
	.byte $c0,$c1,$c1,$c0,$00,$03
@env22:
	.byte $00,$c0,$bf,$be,$02,$bf,$c1,$c2,$02,$c1,$00,$01
@env23:
	.byte $c0,$c0,$cc,$00,$00
@env24:
	.byte $c0,$c0,$ca,$00,$00
@env25:
	.byte $c0,$c0,$c2,$00,$00
@env26:
	.byte $c0,$c0,$c6,$00,$00
@env27:
	.byte $c0,$c0,$c7,$00,$00
@env28:
	.byte $c0,$c0,$c5,$00,$00
@env29:
	.byte $00,$c0,$bc,$c0,$c4,$00,$01
@env30:
	.byte $c0,$c0,$c4,$00,$00
@env31:
	.byte $c0,$c1,$02,$c0,$00,$03
@env32:
	.byte $00,$c6,$c9,$cf,$00,$03
@env33:
	.byte $00,$cc,$ca,$c9,$c8,$c7,$c7,$c6,$c5,$c5,$c4,$c3,$02,$c2,$c2,$c1,$00,$0f
@env34:
	.byte $cd,$7f,$00,$00

@samples:
	.byte $07+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$09,$40 ; 00 piano-002 (Pitch:9)
	.byte $07+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0c,$40 ; 01 piano-002 (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$01,$40 ; 02 piano-003 (Pitch:1)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$02,$40 ; 03 piano-003 (Pitch:2)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$03,$40 ; 04 piano-003 (Pitch:3)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$04,$40 ; 05 piano-003 (Pitch:4)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$05,$40 ; 06 piano-003 (Pitch:5)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$06,$40 ; 07 piano-003 (Pitch:6)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$07,$40 ; 08 piano-003 (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$08,$40 ; 09 piano-003 (Pitch:8)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0a,$40 ; 0a piano-003 (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0b,$40 ; 0b piano-003 (Pitch:11)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$03,$40 ; 0c piano-004 (Pitch:3)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$04,$40 ; 0d piano-004 (Pitch:4)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$07,$40 ; 0e piano-004 (Pitch:7)

@song0ch0:
	.byte $46, $05
@song0ref3:
	.byte $7e
@song0ref4:
	.byte $4f, $02
@song0ref6:
	.byte $86, $35, $74, $80, $29, $7e, $86, $30, $74, $80, $35, $7e, $86, $2e, $74, $80, $30, $7e, $86, $29, $74, $80, $2e, $7e
	.byte $86, $35, $74, $80, $29, $7e, $86, $30, $74, $80, $35, $7e, $86, $2e, $74, $80, $30, $7e, $86, $29, $74, $80, $2e, $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
@song0ch0loop:
	.byte $4c
	.byte $41, $10
	.word @song0ref3
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $41, $10
	.word @song0ref3
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $41, $10
	.word @song0ref3
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
@song0ref112:
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $02
@song0ref118:
	.byte $1d, $75, $81, $7a, $4b, .lobyte(@env28), .hibyte(@env28), $1f, $75, $4b, .lobyte(@env23), .hibyte(@env23), $1d, $7a
	.byte $4d, $21, $75, $4b, .lobyte(@env28), .hibyte(@env28), $1f, $7a, $4d, $1d, $75, $81, $7a, $4b, .lobyte(@env23), .hibyte(@env23)
	.byte $1d, $75, $81, $7a, $4b, .lobyte(@env28), .hibyte(@env28), $1f, $75, $4b, .lobyte(@env23), .hibyte(@env23), $1d, $7a
	.byte $4d, $21, $75, $4b, .lobyte(@env28), .hibyte(@env28), $1f, $7a, $4d, $1d, $75, $81, $7a, $4b, .lobyte(@env23), .hibyte(@env23)
	.byte $4f, $03
	.byte $41, $10
	.word @song0ref118
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref118
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref118
	.byte $41, $10
	.word @song0ref112
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref118
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref118
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref118
	.byte $41, $10
	.word @song0ref112
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref118
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref118
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref118
	.byte $41, $10
	.word @song0ref112
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref118
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref118
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref118
@song0ref291:
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $02
@song0ref297:
	.byte $1d, $75, $4b, .lobyte(@env10), .hibyte(@env10), $4c, $22, $7a, $4b, .lobyte(@env26), .hibyte(@env26), $1f, $75, $4b
	.byte .lobyte(@env23), .hibyte(@env23), $1d, $7a, $4b, .lobyte(@env30), .hibyte(@env30), $20, $75, $4b, .lobyte(@env26), .hibyte(@env26)
	.byte $1f, $7a, $4b, .lobyte(@env10), .hibyte(@env10), $4c, $22, $75, $4b, .lobyte(@env30), .hibyte(@env30), $20, $7a, $4b
	.byte .lobyte(@env23), .hibyte(@env23), $1d, $75, $4b, .lobyte(@env10), .hibyte(@env10), $4c, $22, $7a, $4b, .lobyte(@env26)
	.byte .hibyte(@env26), $1f, $75, $4b, .lobyte(@env23), .hibyte(@env23), $1d, $7a, $4b, .lobyte(@env30), .hibyte(@env30), $20
	.byte $75, $4b, .lobyte(@env26), .hibyte(@env26), $1f, $7a, $4b, .lobyte(@env10), .hibyte(@env10), $4c, $22, $75, $4b, .lobyte(@env30)
	.byte .hibyte(@env30), $20, $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
@song0ref404:
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $02
@song0ref410:
	.byte $1d, $75, $4b, .lobyte(@env28), .hibyte(@env28), $1d, $7a, $4d, $20, $75, $4b, .lobyte(@env23), .hibyte(@env23), $1d
	.byte $7a, $4b, .lobyte(@env25), .hibyte(@env25), $22, $75, $4b, .lobyte(@env28), .hibyte(@env28), $20, $7a, $4d, $1d, $75
	.byte $4b, .lobyte(@env25), .hibyte(@env25), $22, $7a, $4b, .lobyte(@env23), .hibyte(@env23), $1d, $75, $4b, .lobyte(@env28)
	.byte .hibyte(@env28), $1d, $7a, $4d, $20, $75, $4b, .lobyte(@env23), .hibyte(@env23), $1d, $7a, $4b, .lobyte(@env25), .hibyte(@env25)
	.byte $22, $75, $4b, .lobyte(@env28), .hibyte(@env28), $20, $7a, $4d, $1d, $75, $4b, .lobyte(@env25), .hibyte(@env25), $22
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref410
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref410
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref410
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref404
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref410
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref410
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref410
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
@song0ref685:
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $02
@song0ref691:
	.byte $20, $75, $81, $7a, $4b, .lobyte(@env28), .hibyte(@env28), $22, $75, $4b, .lobyte(@env23), .hibyte(@env23), $20, $7a
	.byte $4d, $24, $75, $4b, .lobyte(@env28), .hibyte(@env28), $22, $7a, $4d, $20, $75, $81, $7a, $4b, .lobyte(@env23), .hibyte(@env23)
	.byte $20, $75, $81, $7a, $4b, .lobyte(@env28), .hibyte(@env28), $22, $75, $4b, .lobyte(@env23), .hibyte(@env23), $20, $7a
	.byte $4d, $24, $75, $4b, .lobyte(@env28), .hibyte(@env28), $22, $7a, $4d, $20, $75, $81, $7a, $4b, .lobyte(@env23), .hibyte(@env23)
	.byte $4f, $03
	.byte $41, $10
	.word @song0ref691
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref691
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref691
	.byte $41, $10
	.word @song0ref685
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref691
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref691
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref691
	.byte $41, $10
	.word @song0ref685
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref691
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref691
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref691
	.byte $41, $10
	.word @song0ref685
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref691
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref691
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref691
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref404
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref410
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref410
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref410
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref404
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref410
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref410
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref410
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $00
	.byte $41, $10
	.word @song0ref297
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $01
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $41, $10
	.word @song0ref291
	.byte $7a, $4b, .lobyte(@env23), .hibyte(@env23), $4f, $03
	.byte $41, $10
	.word @song0ref297
	.byte $77, $4b, .lobyte(@env10), .hibyte(@env10), $4c
@song0ref1205:
	.byte $4f, $02
@song0ref1207:
	.byte $35, $73, $29, $77, $31, $73, $35, $77, $30, $73, $31, $77, $29, $73, $30, $77, $35, $73, $29, $77, $31, $73, $35, $77
	.byte $30, $73, $31, $77, $29, $73, $30, $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1205
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1205
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1205
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
@song0ref1298:
	.byte $77, $4f, $02
@song0ref1301:
	.byte $35, $73, $2e, $77, $31, $73, $35, $77, $30, $73, $31, $77, $2e, $73, $30, $77, $35, $73, $2e, $77, $31, $73, $35, $77
	.byte $30, $73, $31, $77, $2e, $73, $30, $77
	.byte $41, $10
	.word @song0ref1301
	.byte $77
	.byte $41, $10
	.word @song0ref1301
	.byte $77
	.byte $41, $10
	.word @song0ref1301
	.byte $41, $10
	.word @song0ref1298
	.byte $77
	.byte $41, $10
	.word @song0ref1301
	.byte $77
	.byte $41, $10
	.word @song0ref1301
	.byte $77
	.byte $41, $10
	.word @song0ref1301
	.byte $77
	.byte $41, $10
	.word @song0ref1205
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1205
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
	.byte $77
	.byte $41, $10
	.word @song0ref1207
@song0ref1391:
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $02
@song0ref1397:
	.byte $1d, $75, $4b, .lobyte(@env10), .hibyte(@env10), $4c, $22, $7a, $4b, .lobyte(@env24), .hibyte(@env24), $1f, $75, $4d
	.byte $1d, $7a, $4b, .lobyte(@env27), .hibyte(@env27), $20, $75, $4b, .lobyte(@env24), .hibyte(@env24), $1f, $7a, $4b, .lobyte(@env10)
	.byte .hibyte(@env10), $4c, $22, $75, $4b, .lobyte(@env27), .hibyte(@env27), $20, $7a, $4b, .lobyte(@env24), .hibyte(@env24)
	.byte $1d, $75, $4b, .lobyte(@env10), .hibyte(@env10), $4c, $22, $7a, $4b, .lobyte(@env24), .hibyte(@env24), $1f, $75, $4d
	.byte $1d, $7a, $4b, .lobyte(@env27), .hibyte(@env27), $20, $75, $4b, .lobyte(@env24), .hibyte(@env24), $1f, $7a, $4b, .lobyte(@env10)
	.byte .hibyte(@env10), $4c, $22, $75, $4b, .lobyte(@env27), .hibyte(@env27), $20, $7a, $4b, .lobyte(@env24), .hibyte(@env24)
	.byte $4f, $03
	.byte $41, $10
	.word @song0ref1397
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $00
	.byte $41, $10
	.word @song0ref1397
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $01
	.byte $41, $10
	.word @song0ref1397
	.byte $41, $10
	.word @song0ref1391
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $03
	.byte $41, $10
	.word @song0ref1397
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $00
	.byte $41, $10
	.word @song0ref1397
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $01
	.byte $41, $10
	.word @song0ref1397
	.byte $41, $10
	.word @song0ref1391
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $03
	.byte $41, $10
	.word @song0ref1397
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $00
	.byte $41, $10
	.word @song0ref1397
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $01
	.byte $41, $10
	.word @song0ref1397
	.byte $41, $10
	.word @song0ref1391
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $03
	.byte $41, $10
	.word @song0ref1397
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $00
	.byte $41, $10
	.word @song0ref1397
	.byte $7a, $4b, .lobyte(@env24), .hibyte(@env24), $4f, $01
	.byte $41, $10
	.word @song0ref1397
	.byte $7e, $4b, .lobyte(@env10), .hibyte(@env10), $4c
	.byte $41, $10
	.word @song0ref4
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $7e
	.byte $41, $10
	.word @song0ref6
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $00, $fd
@song0ch1loop:
	.byte $4c, $00, $fd, $7f, $4f, $00, $80
@song0ref1623:
	.byte $1d, $75, $22, $7f, $1f, $75, $1d, $7f, $21, $75, $1f, $7f, $22, $75, $21, $7f, $4f, $01, $1d, $75, $22, $7f, $1f, $75
	.byte $1d, $7f, $21, $75, $1f, $7f, $22, $75, $21, $7f, $4f, $02, $1d, $75, $22, $7f, $1f, $75, $1d, $7f, $21, $75, $1f, $7f
	.byte $22, $75, $21, $7f, $4f, $03, $1d, $75, $22, $7f, $1f, $75, $1d, $7f, $21, $75, $1f, $7f, $22, $75, $21, $7f, $4f, $00
	.byte $41, $20
	.word @song0ref1623
	.byte $7f, $4f, $00
	.byte $41, $20
	.word @song0ref1623
	.byte $7f, $4f, $00
	.byte $41, $20
	.word @song0ref1623
	.byte $7d, $51, $f9, $30, $49, .lobyte(@env18), .hibyte(@env18), $8c, $29, $87, $51, $0a, $c0, $85, $8c, $29, $76, $81, $7d
	.byte $24, $76, $29, $7d, $2b, $76, $24, $7d, $51, $fd, $40, $2d, $89, $49, .lobyte(@env15), .hibyte(@env15), $8f, $7d, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $8e, $2d, $72, $81, $7d, $2e, $76, $2d, $7f, $51, $fb, $30, $49, .lobyte(@env14)
	.byte .hibyte(@env14), $30, $8f, $7f, $51, $f9, $d0, $8e, $30, $7f, $51, $fc, $a0, $32, $85, $7f, $51, $fb, $c0, $30, $81
	.byte $7f, $2e, $81, $77, $30, $81, $7f, $2d, $81, $77, $2e, $81, $7f, $2b, $81, $77, $2d, $81, $7f, $29, $77, $2b, $7f, $81
	.byte $77, $29, $7f, $51, $fc, $a0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2d, $81, $49, .lobyte(@env29), .hibyte(@env29)
	.byte $83, $7f, $51, $fb, $c0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $83, $7f, $51, $fb, $c0, $8e, $2e, $81, $7f, $51
	.byte $fe, $00, $4f, $02, $30, $8d, $49, .lobyte(@env9), .hibyte(@env9), $9f, $87, $7f, $51, $f3, $b0, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $8e, $29, $71, $51, $fc, $00, $81, $7f, $51, $f3, $b0, $2b, $76, $51, $f3, $20, $29, $7f, $51
	.byte $f3, $b0, $2d, $76, $51, $f3, $20, $2b, $7f, $51, $f3, $b0, $2e, $76, $51, $f3, $20, $2d, $7f, $51, $fc, $50, $2d, $8d
	.byte $87, $7a, $51, $fe, $50, $49, .lobyte(@env22), .hibyte(@env22), $8f, $7d, $51, $f9, $30, $49, .lobyte(@env18), .hibyte(@env18)
	.byte $8c, $29, $87, $51, $0a, $c0, $85, $8c, $29, $76, $81, $7d, $24, $76, $29, $7d, $2b, $76, $24, $7d, $51, $fd, $40, $30
	.byte $89, $49, .lobyte(@env15), .hibyte(@env15), $8f, $7d, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $30, $72, $81
	.byte $7d, $32, $76, $30, $7f, $51, $fb, $30, $49, .lobyte(@env14), .hibyte(@env14), $33, $8f, $7f, $51, $f9, $d0, $8e, $33
	.byte $7f, $51, $fc, $a0, $35, $85, $7f, $51, $fb, $c0, $33, $81, $7f, $32, $81, $77, $33, $81, $7f, $30, $81, $77, $32, $81
	.byte $7f, $2e, $81, $77, $30, $81, $7f, $2b, $77, $2e, $7f, $29, $77, $2b, $7f, $51, $fc, $a0, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $2d, $81, $49, .lobyte(@env29), .hibyte(@env29), $83, $7f, $51, $fb, $c0, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $83, $7f, $51, $fb, $c0, $8e, $2e, $81, $7f, $51, $fe, $00, $4f, $02, $30, $8d, $49, .lobyte(@env9), .hibyte(@env9)
	.byte $9f, $87, $7f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $35, $81, $37, $81, $39
@song0ref2071:
	.byte $85, $51, $fd, $20, $8f, $49, .lobyte(@env4), .hibyte(@env4), $97, $7f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e
	.byte $3a, $89, $76, $3a, $89, $74, $3a, $89, $72, $3a, $89, $71, $3a, $85, $7f, $38, $81, $37, $81, $35, $89, $76, $35, $89
	.byte $74, $35, $89, $72, $35, $89, $7f, $33, $81, $35, $81, $37, $81, $33, $81, $35, $85, $30, $89, $76, $30, $89, $74, $30
	.byte $89, $72, $30, $89, $71, $30, $8d, $7f, $2b, $81, $2c, $81, $2e, $85, $2c, $89, $76, $2c, $89, $74, $2c, $89, $72, $2c
	.byte $81, $7f, $30, $89, $76, $30, $89, $74, $30, $89, $72, $30, $89, $71, $30, $85, $7f, $31, $81, $33, $81, $35, $89, $76
	.byte $35, $89, $74, $35, $89, $72, $35, $89, $7f, $37, $81, $38, $81, $3a, $81, $37, $81, $38, $85, $35, $89, $76, $35, $89
	.byte $74, $35, $89, $72, $35, $81, $7f, $2e, $81, $30, $81, $33, $81, $30, $81, $35, $85, $30, $89, $76, $30, $89, $74, $30
	.byte $89, $72, $30, $89, $71, $30
@song0ref2236:
	.byte $85, $7a, $51, $fc, $00, $4b, .lobyte(@env12), .hibyte(@env12), $4f, $01, $80
@song0ref2247:
	.byte $22, $8d, $7a, $51, $fc, $00, $8f, $7a, $51, $fb, $20, $8b, $51, $06, $90, $87, $72, $51, $05, $50, $83, $72, $51, $05
	.byte $50, $83, $72, $51, $05, $50, $83, $7a, $51, $fc, $00, $4b, .lobyte(@env13), .hibyte(@env13), $20, $8d, $7a, $51, $fc
	.byte $00, $8f, $7a, $51, $fb, $20, $8b, $51, $06, $90, $87, $72, $51, $05, $50, $83, $72, $51, $05, $50, $83, $72, $51, $05
	.byte $50, $83, $7a, $51, $fc, $00, $4b, .lobyte(@env12), .hibyte(@env12), $4f, $01
	.byte $41, $10
	.word @song0ref2247
	.byte $7a, $51, $fc, $00, $4b, .lobyte(@env12), .hibyte(@env12), $4f, $01
	.byte $41, $10
	.word @song0ref2247
	.byte $7a, $51, $fc, $00, $4b, .lobyte(@env12), .hibyte(@env12), $4f, $01
	.byte $41, $10
	.word @song0ref2247
	.byte $7d, $51, $f9, $30, $49, .lobyte(@env18), .hibyte(@env18), $4b, .lobyte(@env10), .hibyte(@env10), $4c, $8c, $2c, $87
	.byte $51, $0a, $c0, $85, $8c, $2c, $76, $81, $7d, $27, $76, $2c, $7d, $2e, $76, $27, $7d, $51, $fd, $40, $30, $89, $49, .lobyte(@env15)
	.byte .hibyte(@env15), $8f, $7d, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $30, $72, $81, $7d, $31, $76, $30, $7f, $51
	.byte $fb, $30, $49, .lobyte(@env14), .hibyte(@env14), $33, $8f, $7f, $51, $f9, $d0, $8e, $33, $7f, $51, $fc, $a0, $35, $85
	.byte $7f, $51, $fb, $c0, $33, $81, $7f, $31, $81, $77, $33, $81, $7f, $30, $81, $77, $31, $81, $7f, $2e, $81, $77, $30, $81
	.byte $7f, $2c, $77, $2e, $7f, $81, $77, $2c, $7f, $51, $fc, $a0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $30, $81, $49
	.byte .lobyte(@env29), .hibyte(@env29), $83, $7f, $51, $fb, $c0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $83, $7f, $51
	.byte $fb, $c0, $8e, $31, $81, $7f, $51, $fe, $00, $4f, $02, $33, $8d, $49, .lobyte(@env9), .hibyte(@env9), $9f, $87, $7f
	.byte $51, $f3, $b0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $2c, $71, $51, $fc, $00, $81, $7f, $51, $f3, $b0, $2e
	.byte $76, $51, $f3, $20, $2c, $7f, $51, $f3, $b0, $30, $76, $51, $f3, $20, $2e, $7f, $51, $f3, $b0, $31, $76, $51, $f3, $20
	.byte $30, $7f, $51, $fc, $50, $30, $8d, $87, $7a, $51, $fe, $50, $49, .lobyte(@env22), .hibyte(@env22), $8f, $7d, $51, $f9
	.byte $30, $49, .lobyte(@env18), .hibyte(@env18), $8c, $2c, $87, $51, $0a, $c0, $85, $8c, $2c, $76, $81, $7d, $27, $76, $2c
	.byte $7d, $2e, $76, $27, $7d, $51, $fd, $40, $33, $89, $49, .lobyte(@env15), .hibyte(@env15), $8f, $7d, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $8e, $33, $72, $81, $7d, $35, $76, $33, $7f, $51, $fb, $30, $49, .lobyte(@env14), .hibyte(@env14)
	.byte $36, $8f, $7f, $51, $f9, $d0, $8e, $36, $7f, $51, $fc, $a0, $38, $85, $7f, $51, $fb, $c0, $36, $81, $7f, $35, $81, $77
	.byte $36, $81, $7f, $33, $81, $77, $35, $81, $7f, $31, $81, $77, $33, $81, $7f, $2e, $77, $31, $7f, $2c, $77, $2e, $7f, $51
	.byte $fc, $a0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $30, $81, $49, .lobyte(@env29), .hibyte(@env29), $83, $7f, $51
	.byte $fb, $c0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $83, $7f, $51, $fb, $c0, $8e, $31, $81, $7f, $51, $fe, $00, $4f
	.byte $02, $33, $8d, $49, .lobyte(@env9), .hibyte(@env9), $9f, $87, $7f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $38
	.byte $81, $3a, $81, $3c
	.byte $41, $11
	.word @song0ref2071
	.byte $38, $89, $76, $38, $89, $74, $38, $89, $72, $38, $89, $7f, $33, $81, $35, $81, $37, $81, $33, $81, $35, $85, $3c, $89
	.byte $76, $3c, $89, $74, $3c, $89, $72, $3c, $89, $71, $3c, $8d, $7f, $27, $81, $29, $81, $2b, $85, $29, $89, $76, $29, $89
	.byte $74, $29, $89, $72, $29, $81, $7f, $38, $89, $76, $38, $89, $74, $38, $89, $72, $38, $89, $71, $38, $85, $7f, $37, $81
	.byte $38, $81, $3a, $89, $76, $3a, $89, $74, $3a, $89, $72, $3a, $89, $7f, $38, $81, $3a, $81, $3c, $81, $3d, $81, $3c, $85
	.byte $38, $89, $76, $38, $89, $74, $38, $89, $72, $38, $81, $7f, $35, $81, $37, $81, $38, $81, $3a, $81, $38, $85, $35, $89
	.byte $76, $35, $89, $74, $35, $89, $72, $35, $89, $71, $35
	.byte $41, $11
	.word @song0ref2236
	.byte $7a, $51, $fc, $00, $4b, .lobyte(@env12), .hibyte(@env12), $4f, $01
	.byte $41, $10
	.word @song0ref2247
	.byte $7a, $51, $fc, $00, $4b, .lobyte(@env12), .hibyte(@env12), $4f, $01
	.byte $41, $10
	.word @song0ref2247
	.byte $7a, $51, $fc, $00, $4b, .lobyte(@env12), .hibyte(@env12), $4f, $01
	.byte $41, $10
	.word @song0ref2247
	.byte $7a, $51, $fc, $00, $4b, .lobyte(@env12), .hibyte(@env12)
@song0ref2897:
	.byte $4f, $01, $1d, $8d, $7a, $51, $fc, $00, $8f, $7a, $51, $fb, $20, $8b, $51, $06, $90, $87, $72, $51, $05, $50, $83, $72
	.byte $51, $05, $50, $83, $72, $51, $05, $50, $83, $7a, $51, $fc, $00, $8f, $7a, $51, $fc, $00, $8f, $7a, $51, $fb, $20, $8b
	.byte $51, $06, $90, $87, $72, $51, $05, $50, $83, $72, $51, $05, $50, $83, $72, $51, $05, $50, $83, $7a, $51, $fc, $00, $4d
	.byte $41, $0f
	.word @song0ref2897
	.byte $7a, $51, $fc, $00, $4d
	.byte $41, $0f
	.word @song0ref2897
	.byte $7a, $51, $fc, $00, $4d
	.byte $41, $0f
	.word @song0ref2897
	.byte $7f, $4b, .lobyte(@env10), .hibyte(@env10), $4c, $90, $24, $89, $78, $24, $89, $76, $24, $89, $75, $24, $89, $72, $24
	.byte $85, $7f, $27, $81, $29, $81, $2b, $89, $78, $2b, $89, $76, $2b, $89, $75, $2b, $89, $7f, $2e, $89, $76, $2e, $81, $7f
	.byte $2d, $85, $29, $85, $24, $85, $22, $89, $78, $22, $81, $7f, $21, $89, $78, $21, $81, $7f, $29, $89, $78, $29, $89, $76
	.byte $29, $89, $75, $29, $89, $72, $29, $89, $71, $29, $89, $7f, $2b, $89, $78, $2b, $89, $76, $2b, $89, $75, $2b, $89, $72
	.byte $2b, $85, $7f, $2c, $81, $2e, $81, $30, $89, $78, $30, $89, $76, $30, $89, $75, $30, $89, $7f, $35, $89, $76, $35, $81
	.byte $7f, $37, $85, $35, $85, $30, $85, $2e, $89, $78, $2e, $81, $7f, $2d, $89, $78, $2d, $81, $7f, $35, $89, $78, $35, $89
	.byte $76, $35, $89, $75, $35, $89, $72, $35, $89, $71, $35, $89, $7f, $2c, $89, $78, $2c, $89, $76, $2c, $85, $7f, $2b, $89
	.byte $78, $2b, $89, $7f, $2c, $81, $2b, $81, $29, $89, $78, $29, $89, $76, $29, $85, $7f, $29, $85, $2b, $85, $2c, $85, $2e
	.byte $85, $30, $89, $78, $30, $89, $76, $30, $89, $75, $30, $89, $72, $30, $85, $7f, $37, $85, $38, $89, $78, $38, $81, $7f
	.byte $37, $85, $35, $89, $78, $35, $89, $76, $35, $89, $75, $35, $81, $7f, $2e, $89, $78, $2e, $89, $76, $2e, $85, $7f, $2c
	.byte $89, $78, $2c, $89, $7f, $2e, $81, $2c, $81, $2b, $89, $78, $2b, $89, $76, $2b, $85, $7f, $2b, $85, $2c, $85, $2e, $85
	.byte $30, $85, $30, $89, $78, $30, $89, $76, $30, $89, $75, $30, $89, $7f, $38, $85, $3a, $85, $3c, $89, $78, $3c, $89, $76
	.byte $3c, $89, $75, $3c, $89, $73, $3c, $89, $71, $3c, $81, $7d, $51, $f9, $10, $8c, $29, $89, $51, $0a, $70, $83, $7d, $29
	.byte $76, $81, $7d, $24, $76, $81, $7d, $2b, $76, $81, $7d, $51, $fd, $40, $2c, $85, $49, .lobyte(@env15), .hibyte(@env15)
	.byte $93, $7d, $51, $fc, $c0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8c, $2c, $76, $51, $fc, $50, $81, $7a, $51, $fc
	.byte $90, $2e, $76, $51, $fc, $50, $2c, $7d, $51, $fd, $a0, $30, $85, $7d, $51, $fc, $b0, $2e, $81, $7f, $51, $fe, $00, $2c
	.byte $8f, $49, .lobyte(@env15), .hibyte(@env15), $9d, $83, $7d, $51, $f9, $10, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $8c, $2c, $89, $51, $0a, $70, $83, $7d, $2c, $76, $81, $7d, $29, $76, $81, $7d, $2c, $76, $81, $7d, $51, $fd, $40, $2e
	.byte $85, $49, .lobyte(@env15), .hibyte(@env15), $93, $7d, $51, $fc, $c0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8c
	.byte $30, $76, $51, $fc, $50, $2e, $7a, $51, $fc, $90, $31, $76, $51, $fc, $50, $30, $7d, $51, $fd, $a0, $33, $85, $7d, $51
	.byte $fc, $b0, $31, $81, $7f, $51, $fe, $00, $30, $8f, $49, .lobyte(@env15), .hibyte(@env15), $9d, $83, $7d, $51, $f9, $10
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $8c, $30, $89, $51, $0a, $70, $83, $7d, $35, $76, $30, $7d, $30, $76, $35
	.byte $7d, $37, $76, $30, $7d, $51, $fd, $40, $38, $85, $49, .lobyte(@env15), .hibyte(@env15), $93, $7d, $51, $fc, $c0, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $8c, $38, $76, $51, $fc, $50, $38, $7a, $51, $fc, $90, $3a, $76, $51, $fc, $50
	.byte $38, $7d, $51, $fd, $a0, $3c, $85, $7d, $51, $fc, $b0, $3a, $81, $7f, $51, $fe, $00, $38, $8f, $49, .lobyte(@env15)
	.byte .hibyte(@env15), $9d, $83, $7d, $51, $f9, $10, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8c, $35, $89, $51, $0a, $70
	.byte $83, $7d, $35, $76, $35, $7d, $30, $76, $35, $7d, $37, $76, $35, $7d, $51, $fd, $40, $38, $85, $49, .lobyte(@env15)
	.byte .hibyte(@env15), $93, $7d, $51, $fc, $c0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8c, $38, $76, $51, $fc, $50, $38
	.byte $7a, $51, $fc, $90, $3a, $76, $51, $fc, $50, $38, $7f, $51, $fe, $00, $3c, $9b, $49, .lobyte(@env15), .hibyte(@env15)
	.byte $91, $87, $7d, $51, $fc, $c0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8c, $39, $72, $51, $fc, $10, $81, $7d, $51
	.byte $fc, $c0, $3a, $76, $51, $fc, $50, $39, $7d, $51, $fe, $00, $49, .lobyte(@env14), .hibyte(@env14), $3c, $a7, $d5, $42
	.word @song0ch1loop
@song0ch2:
	.byte $8f, $00, $ed
@song0ch2loop:
	.byte $8f, $00, $ed
@song0ref3651:
	.byte $88
@song0ref3652:
	.byte $40, $0a, $95, $40, $0a, $ad, $40, $0a, $8d, $40, $0a, $a5, $40, $0a, $95, $40, $0a, $ad, $40, $0a, $8d, $40, $0a, $a5
	.byte $05, $95, $0c, $ad, $03, $8d, $0a, $a5, $05, $95, $0c, $ad, $03, $8d, $0a, $a5, $09, $95, $0a, $a5, $0c, $95, $0e, $a5
	.byte $09, $95, $0a, $a5, $0c, $95, $0e
@song0ref3707:
	.byte $a5
@song0ref3708:
	.byte $01, $95, $08, $ad, $08, $8d, $01, $95, $80, $50, $22, $2e, $26, $81, $0c, $89, $88, $0a, $95, $80, $08, $ad, $07, $8d
	.byte $08, $95, $50, $22, $2e, $26, $81, $08, $89, $88
	.byte $41, $18
	.word @song0ref3708
@song0ref3745:
	.byte $88, $05, $95, $0c, $ad, $01, $8d, $0a, $95, $80, $50, $22, $2e, $26, $81, $0a, $89, $88, $05, $95, $0c, $ad, $01, $8d
	.byte $0a, $95, $80, $50, $22, $2e, $26, $81, $0a, $89
	.byte $41, $18
	.word @song0ref3745
	.byte $88, $14, $95, $1b, $ad, $12, $8d, $80, $19, $a5, $88, $14, $95, $1b, $ad, $12, $8d, $80, $19, $a5, $88, $0c, $95, $0d
	.byte $a5, $0f, $95, $11, $a5, $0c, $95, $0d, $a5, $0f, $95, $11
	.byte $41, $19
	.word @song0ref3707
	.byte $88
	.byte $41, $18
	.word @song0ref3708
	.byte $41, $18
	.word @song0ref3745
	.byte $41, $18
	.word @song0ref3745
	.byte $41, $18
	.word @song0ref3745
	.byte $41, $18
	.word @song0ref3745
	.byte $41, $10
	.word @song0ref3651
	.byte $41, $10
	.word @song0ref3652
	.byte $08, $95, $08, $85, $80, $07, $95, $08, $81, $07, $81, $05, $85, $88, $05, $8d, $05, $85, $80, $05, $85, $07, $85, $08
	.byte $85, $0a, $85, $88, $0c, $95, $80, $0c, $9d, $07, $85, $08, $85, $88, $08, $85, $80, $07, $85, $88, $05, $a5, $0a, $9d
	.byte $08, $95, $80, $0a, $81, $08, $81, $07, $9d, $07, $85, $08, $85, $0a, $85, $0c, $85, $88, $0c, $ad, $14, $85, $80, $16
	.byte $85, $18, $85, $88, $0c, $a5, $43, $50, $15, $18, $12, $8d
@song0ref3927:
	.byte $40, $0a, $95, $40, $0a, $ad, $40, $0a, $8d, $40, $0a, $95, $80, $50, $22, $2e, $26, $81, $40, $0a, $87, $47, $02, $88
	.byte $05, $40, $0a, $95, $40, $0a, $ad, $40, $0a, $8d, $40, $0a, $95, $80, $50, $22, $2e, $26, $81, $40, $0a, $87, $47, $02
	.byte $88, $05
	.byte $41, $1a
	.word @song0ref3927
	.byte $8f, $00, $ed, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff
@song0ch3loop:
	.byte $87, $82
@song0ref3990:
	.byte $14, $81, $14, $89, $14, $81, $14, $89, $14, $81, $14, $89, $14, $81, $14, $89
	.byte $41, $0f
	.word @song0ref3990
@song0ref4009:
	.byte $81
@song0ref4010:
	.byte $84, $18, $85, $82, $14, $81, $14, $89, $84, $14, $81, $82, $14, $89, $14, $81, $14, $89, $14, $81, $14, $89, $84, $14
	.byte $81, $82, $14, $89, $84, $14, $81, $82, $14, $89, $14, $81, $14, $89, $14, $81, $14
	.byte $41, $22
	.word @song0ref4009
	.byte $41, $22
	.word @song0ref4009
	.byte $41, $22
	.word @song0ref4009
@song0ref4060:
	.byte $81
@song0ref4061:
	.byte $84, $18
@song0ref4063:
	.byte $85, $82, $14, $81, $14, $89, $84, $18, $81, $82, $14, $89, $14, $81, $14, $89, $14, $81, $14
	.byte $41, $12
	.word @song0ref4060
	.byte $41, $12
	.word @song0ref4060
	.byte $41, $0e
	.word @song0ref4060
@song0ref4091:
	.byte $81, $71, $51, $09, $f0, $80, $18, $19
@song0ref4099:
	.byte $1a, $1b, $1c, $1d, $1e, $1f, $51, $fc, $00, $1a, $1b, $81, $1c, $81, $1d, $81, $1e, $83, $1f, $81, $7f, $84, $18, $81
	.byte $82, $14, $89, $14, $81, $14, $89, $14, $81, $14
@song0ref4133:
	.byte $89, $84, $18, $81, $82, $14, $89, $84, $18, $81, $82, $14, $89, $14, $81, $14, $81, $8a, $1f, $85, $82, $14, $81, $14
	.byte $81, $84, $14
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $13
	.word @song0ref4133
	.byte $41, $11
	.word @song0ref4061
	.byte $41, $0e
	.word @song0ref4060
	.byte $81, $8a, $18, $81, $73, $51, $0a, $f0, $80, $1a, $1b, $1c, $1d, $1e, $1f
	.byte $41, $21
	.word @song0ref4010
	.byte $41, $22
	.word @song0ref4009
	.byte $41, $12
	.word @song0ref4060
	.byte $41, $12
	.word @song0ref4060
	.byte $41, $12
	.word @song0ref4060
	.byte $41, $0e
	.word @song0ref4060
	.byte $41, $33
	.word @song0ref4091
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $13
	.word @song0ref4133
	.byte $41, $11
	.word @song0ref4061
	.byte $41, $0e
	.word @song0ref4060
	.byte $81, $8a, $18, $81, $73, $51, $0a, $f0, $80
	.byte $41, $2f
	.word @song0ref4099
	.byte $41, $21
	.word @song0ref4010
	.byte $41, $22
	.word @song0ref4009
	.byte $41, $22
	.word @song0ref4009
	.byte $41, $22
	.word @song0ref4009
	.byte $41, $22
	.word @song0ref4009
	.byte $41, $22
	.word @song0ref4009
	.byte $41, $22
	.word @song0ref4009
	.byte $81, $84, $14
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $14
	.word @song0ref4133
	.byte $41, $10
	.word @song0ref4063
	.byte $41, $13
	.word @song0ref4133
	.byte $41, $11
	.word @song0ref4061
	.byte $41, $0e
	.word @song0ref4060
	.byte $81, $8a, $18, $81, $73, $51, $0a, $f0, $80
	.byte $41, $11
	.word @song0ref4099
	.byte $87, $7f, $00, $dd, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff
@song0ch4loop:
	.byte $ff, $ff, $ff
@song0ref4388:
	.byte $04, $8d, $04, $85, $08, $8d, $08, $8d, $08, $8d, $03, $8d, $07, $8d, $07, $8d, $07, $85
	.byte $41, $12
	.word @song0ref4388
@song0ref4409:
	.byte $0e, $8d, $0e, $85, $07, $8d, $07, $8d, $07, $85, $08, $8d, $08, $85, $0f, $8d, $0f, $8d, $0f, $85
	.byte $41, $14
	.word @song0ref4409
@song0ref4432:
	.byte $97, $06, $8d, $06, $8d, $06, $8d, $06, $a5, $08, $8d, $07, $8d, $07, $85, $06, $8d, $06, $8d, $06, $8d, $0d, $85, $0d
	.byte $85, $06, $8d, $06, $8d, $06, $85
	.byte $41, $1f
	.word @song0ref4432
@song0ref4466:
	.byte $04, $8d, $04, $85, $08, $8d, $08, $8d, $08, $9d, $07, $8d, $07, $8d, $07, $85
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
@song0ref4491:
	.byte $06, $8d, $06, $85, $0a, $8d, $0a, $8d, $0a, $8d, $05, $8d, $09, $8d, $09, $8d, $09, $85
	.byte $41, $12
	.word @song0ref4491
@song0ref4512:
	.byte $08, $8d, $08, $85, $09, $8d, $09, $8d, $09, $85, $0a, $8d, $0a, $85, $01, $8d, $01, $8d, $01, $85
	.byte $41, $14
	.word @song0ref4512
	.byte $41, $1f
	.word @song0ref4432
	.byte $41, $1f
	.word @song0ref4432
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
	.byte $41, $10
	.word @song0ref4466
	.byte $ff, $ff, $ff, $ef, $01, $81, $09, $81, $08, $81, $04, $81, $06, $9d, $0d, $95, $06, $81, $0d, $81, $04, $9d, $04, $85
	.byte $0d, $85, $06, $85, $07, $85, $08, $b5, $0d, $85, $06, $8d, $0d, $85, $04, $a5, $07, $9d, $06, $95, $07, $81, $06, $81
	.byte $0d, $9d, $0d, $85, $06, $85, $07, $85, $08, $85, $08, $ad, $0b, $85, $0c, $85, $02, $bd
@song0ref4631:
	.byte $00, $81, $04, $81, $04, $81, $04, $81, $00, $81, $04, $81, $04, $81, $04, $81
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $41, $10
	.word @song0ref4631
	.byte $04, $fd, $42
	.word @song0ch4loop
