; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Project uses delayed notes or cuts, you must set FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_ch2=music_data_ch2
.endif

music_data_ch2:
	.byte 3
	.word @instruments
	.word @samples-4
; 00 : intro
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256
; 01 : mirrorpiano_dreamblocksting
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 204,170
; 02 : main
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 307,256

.export music_data_ch2
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env7,@env9,@env0 ; 00 : Marimba (Quiet)
	.word @env6,@env7,@env9,@env0 ; 01 : Marimba (Intro)
	.word @env11,@env7,@env9,@env0 ; 02 : Marimba
	.word @env14,@env7,@env8,@env0 ; 03 : Cymbal
	.word @env16,@env7,@env8,@env0 ; 04 : Reverse Cymbal
	.word @env13,@env12,@env9,@env0 ; 05 : Piano
	.word @env5,@env7,@env1,@env0 ; 06 : Piano (Intro)
	.word @env13,@env7,@env9,@env0 ; 07 : Piano without octave
	.word @env4,@env7,@env8,@env0 ; 08 : DPCM

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c2,$c1,$00,$01
@env2:
	.byte $00,$c0,$b8,$b3,$b5,$bc,$c4,$cb,$cd,$c8,$00,$01
@env3:
	.byte $00,$c4,$c3,$c3,$c2,$c2,$c1,$00,$06
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $00,$ca,$02,$c8,$c8,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$04,$c1,$0a,$c0,$00,$11
@env6:
	.byte $00,$c6,$02,$c5,$c4,$02,$c3,$c2,$00,$07
@env7:
	.byte $c0,$7f,$00,$01
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $00,$c0,$c0,$bf,$06,$c0,$03,$c1,$06,$c0,$00,$01
@env11:
	.byte $00,$c4,$c7,$02,$c5,$c4,$c3,$03,$c2,$00,$08
@env12:
	.byte $b4,$b4,$c0,$00,$02
@env13:
	.byte $00,$cb,$c9,$c9,$c8,$c7,$c7,$c6,$02,$c5,$03,$c4,$04,$c3,$03,$c2,$04,$c1,$06,$c0,$00,$13
@env14:
	.byte $00,$c6,$03,$c5,$07,$c4,$07,$c3,$08,$c2,$07,$c1,$00,$0b
@env15:
	.byte $00,$c0,$bf,$02,$c0,$c0,$c1,$c1,$c1,$00,$01
@env16:
	.byte $00,$c1,$06,$c2,$07,$c3,$07,$c4,$07,$c5,$07,$c6,$00,$0b

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 00 bassdrum (Pitch:15)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$31,$0f,$40 ; 01 hihat1 (Pitch:15)
	.byte $17+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0f,$40 ; 02 hihat2 (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 03 snare (Pitch:15)
	.byte $2f+.lobyte(FAMISTUDIO_DPCM_PTR),$35,$0f,$40 ; 04 snare_quieter (Pitch:15)

@song0ch0:
	.byte $46, $06
@song0ref3:
	.byte $82
@song0ref4:
	.byte $0a, $81, $0d, $81, $11, $81, $15, $81, $19, $81, $1d, $81, $21, $81, $25, $81, $29, $81, $80, $0d, $81, $11, $81, $15
	.byte $81, $19, $81, $7a, $1d, $81, $21, $81, $25, $81, $7f
	.byte $41, $20
	.word @song0ref3
@song0ref42:
	.byte $7f
@song0ref43:
	.byte $82
@song0ref44:
	.byte $08, $81, $0d, $81, $11, $81, $14, $81, $19, $81, $1d, $81, $20, $81, $25, $81, $29, $81, $80, $0d, $81, $11, $81, $14
	.byte $81, $19, $81, $1d, $81, $20, $81, $25, $81
	.byte $41, $20
	.word @song0ref43
@song0ref80:
	.byte $82
@song0ref81:
	.byte $06, $81, $0a, $81, $0d, $81, $11, $81, $16, $81, $19, $81, $1d, $81, $22, $81, $25, $81, $80, $0a, $81, $0d, $81, $11
	.byte $81, $16, $81, $7a, $19, $81, $1d, $81, $22, $81, $7f
	.byte $41, $20
	.word @song0ref80
@song0ref119:
	.byte $7f, $82
@song0ref121:
	.byte $05, $81, $09, $81, $0c, $81, $11, $81, $15, $81, $18, $81, $1d, $81, $21, $81, $24, $81, $80, $09, $81, $0c, $81, $11
	.byte $81, $15, $81, $7a, $18, $81, $1d, $81, $21, $81
	.byte $41, $20
	.word @song0ref119
@song0ch0loop:
	.byte $7f
	.byte $41, $20
	.word @song0ref3
	.byte $7f
	.byte $41, $20
	.word @song0ref3
	.byte $41, $20
	.word @song0ref42
	.byte $41, $20
	.word @song0ref43
	.byte $41, $20
	.word @song0ref80
	.byte $7f
	.byte $41, $20
	.word @song0ref80
	.byte $41, $20
	.word @song0ref119
	.byte $41, $20
	.word @song0ref119
	.byte $7f, $82
@song0ref188:
	.byte $0a, $81, $0d, $81, $11, $81, $15, $81, $19, $81, $1d, $71, $29, $7f, $21, $71, $29, $7f, $25, $72, $29, $7f, $29, $72
	.byte $29, $7f, $80, $0d, $72, $82, $29, $7f, $80, $11, $72, $82, $29, $7f, $80, $15, $72, $82, $29, $7f, $80, $19, $71, $82
	.byte $29, $7a, $80, $1d, $71, $82, $29, $7a, $80, $21, $71, $82, $29, $7a, $80, $25, $71, $82, $29, $7f
	.byte $41, $20
	.word @song0ref188
@song0ref259:
	.byte $7f, $08, $81, $0d, $81, $11, $81, $14, $81, $19, $81, $1d, $71, $29, $7f, $20, $71, $29, $7f, $25, $71, $29, $7f, $29
	.byte $71, $29, $7f, $80, $0d, $71, $82, $29, $7f, $80, $11, $71, $82, $29, $7f, $80, $14, $71, $82, $29, $7f, $80, $19, $71
	.byte $82, $29, $7a, $80, $1d, $71, $82, $29, $7a, $80, $20, $71, $82, $29, $7a, $80, $25, $71, $82, $29
	.byte $41, $20
	.word @song0ref259
@song0ref330:
	.byte $7f, $06, $81, $0a, $81, $0d, $81, $11, $81, $16, $81, $19, $71, $25, $7f, $1d, $71, $25, $7f, $22, $71, $25, $7f, $25
	.byte $71, $25, $7f, $80, $0a, $71, $82, $25, $7f, $80, $0d, $71, $82, $25, $7f, $80, $11, $71, $82, $25, $7f, $80, $16, $71
	.byte $82, $25, $7a, $80, $19, $71, $82, $25, $7a, $80, $1d, $71, $82, $25, $7a, $80, $22, $71, $82, $25
	.byte $41, $20
	.word @song0ref330
@song0ref401:
	.byte $7f, $05, $81, $09, $81, $0c, $81, $11, $81, $15, $81, $18, $71, $24, $7f, $1d, $71, $24, $7f, $21, $71, $24, $7f, $24
	.byte $71, $24, $7f, $80, $09, $71, $82, $24, $7f, $80, $0c, $71, $82, $24, $7f, $80, $11, $71, $82, $24, $7f, $80, $15, $71
	.byte $82, $24, $7a, $80, $18, $71, $82, $24, $7a, $80, $1d, $71, $82, $24, $7a, $80, $21, $71, $82, $24
	.byte $41, $20
	.word @song0ref401
	.byte $7f
	.byte $41, $20
	.word @song0ref188
	.byte $7f
	.byte $41, $20
	.word @song0ref188
	.byte $41, $20
	.word @song0ref259
	.byte $41, $20
	.word @song0ref259
	.byte $41, $20
	.word @song0ref330
	.byte $41, $20
	.word @song0ref330
	.byte $41, $20
	.word @song0ref401
	.byte $41, $20
	.word @song0ref401
	.byte $7f
	.byte $41, $20
	.word @song0ref188
	.byte $7f
	.byte $41, $20
	.word @song0ref188
	.byte $41, $20
	.word @song0ref259
	.byte $41, $20
	.word @song0ref259
	.byte $41, $20
	.word @song0ref330
	.byte $41, $20
	.word @song0ref330
	.byte $41, $20
	.word @song0ref401
	.byte $41, $20
	.word @song0ref401
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $73, $80, $29, $81, $00, $89, $7f
	.byte $41, $12
	.word @song0ref4
	.byte $00, $89, $73, $29, $81, $00, $89, $7f
	.byte $41, $12
	.word @song0ref4
	.byte $00, $89, $77, $29, $81, $00, $89, $7f
	.byte $41, $12
	.word @song0ref44
	.byte $00, $89, $77, $29, $81, $00, $89, $7f
	.byte $41, $12
	.word @song0ref44
	.byte $00, $89, $77, $25, $81, $00, $89, $7f
	.byte $41, $12
	.word @song0ref81
	.byte $00, $89, $77, $25, $81, $00, $89, $7f
	.byte $41, $12
	.word @song0ref81
	.byte $00, $89, $77, $24, $81, $00, $89, $7f
	.byte $41, $12
	.word @song0ref121
	.byte $00, $89, $77, $24, $81, $00, $89, $7f
	.byte $41, $10
	.word @song0ref121
	.byte $8c, $22, $81, $24, $81, $25, $81, $27, $81
@song0ch1loop:
	.byte $7f
@song0ref625:
	.byte $29, $b9, $82, $27, $81, $8c, $25, $b9, $24, $81, $22, $bd, $af, $22, $81, $24, $81, $25, $81, $27, $81, $29, $b9, $47
	.byte $03, $7a, $82, $27, $81, $7f, $8c, $25, $b9, $22, $81, $21, $bd, $77, $80, $24, $81, $00, $89, $7f
	.byte $41, $10
	.word @song0ref121
	.byte $8c, $22, $81, $24, $81, $25, $81, $27, $81
	.byte $41, $1d
	.word @song0ref625
	.byte $bf
@song0ref685:
	.byte $7a, $16, $85, $7f, $21, $8d, $21, $85, $7a, $16, $85, $7f, $22, $8d, $22, $85, $7a, $16, $85, $7f, $24, $8d, $24, $85
	.byte $7a, $16, $85, $7f, $25, $8d, $25, $85, $7a, $14, $85, $7f, $20, $8d, $20, $85, $7a, $14, $85, $7f, $22, $8d, $22, $85
	.byte $7a, $14, $85, $7f, $24, $8d, $24, $85, $7a, $14, $85, $7f, $25, $8d, $25, $85, $7a, $12, $85, $7f, $21, $8d, $21, $85
	.byte $7a, $12, $85, $7f, $22, $8d, $22, $85, $7a, $12, $85, $7f, $24, $8d, $24, $85, $7a, $12, $85, $7f, $25, $8d, $25, $85
	.byte $7a, $11, $85, $7f, $21, $8d, $21, $85, $7a, $11, $85, $7f, $22, $8d, $22, $85, $7a, $11, $85, $7f, $24, $8d, $24, $85
	.byte $7a, $11, $85, $7f, $25, $8d, $25, $85
	.byte $41, $56
	.word @song0ref685
	.byte $7d, $24, $8d, $7b, $24, $8d, $78, $25, $8d, $7c, $22, $85, $42
	.word @song0ch1loop
@song0ch2:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
@song0ch2loop:
	.byte $82
@song0ref841:
	.byte $16, $bd, $16, $bd, $86, $14, $bd, $14, $bd, $82, $12, $bd, $12, $bd, $11, $bd, $11, $bd
	.byte $41, $10
	.word @song0ref841
	.byte $41, $10
	.word @song0ref841
	.byte $41, $10
	.word @song0ref841
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $ab, $88, $1f, $91
@song0ch3loop:
@song0ref883:
	.byte $86, $1f, $9d, $00, $9d, $bf, $bf, $bf, $bf, $bf, $bf, $ab, $88, $1f, $91, $86, $1f, $9d, $00, $9d, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $ab, $88, $1f, $91
	.byte $41, $1a
	.word @song0ref883
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
@song0ch4loop:
@song0ref928:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $41, $10
	.word @song0ref928
	.byte $42
	.word @song0ch4loop
@song1ch0:
	.byte $46, $09, $46, $09, $49, .lobyte(@env10), .hibyte(@env10), $82, $22, $8f, $7e, $81, $7d, $81, $7c, $81, $7b, $81, $7a
	.byte $81, $79, $81, $78, $81, $77, $93, $7f, $49, .lobyte(@env15), .hibyte(@env15), $88, $2e, $8b, $51, $fd, $d0, $81, $51
	.byte $fd, $b0, $81, $51, $fd, $90, $81, $51, $fd, $70, $81, $51, $fd, $50, $81, $51, $fd, $30, $81, $51, $fd, $10, $81, $51
	.byte $fe, $00, $81, $85
@song1ch0loop:
	.byte $7f, $51, $fd, $b0, $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $0a, $81, $46, $08, $7f, $51, $fe, $c0, $0d, $81
	.byte $7f, $51, $fe, $c0, $11, $81, $46, $07, $7f, $51, $fd, $c0, $15, $81, $7f, $51, $fd, $c0, $19, $81, $46, $06, $7f, $51
	.byte $fd, $c0, $1d, $81, $7f, $51, $fd, $c0, $21, $81, $46, $05, $7f, $51, $fd, $d0, $25, $81, $7f, $51, $fd, $d0, $29, $81
	.byte $46, $04, $7f, $51, $fd, $d0, $2d, $81, $7f, $51, $fd, $d0, $31, $81, $46, $03, $7f, $51, $fc, $d0, $35, $81, $7f, $51
	.byte $fc, $d0, $39, $81, $7f, $51, $fc, $d0, $3d, $81, $7f, $51, $fc, $d0, $40, $4d, $81, $7f, $51, $fc, $d0, $40, $51, $81
	.byte $7f, $51, $fc, $d0, $35, $81, $7f, $51, $fc, $d0, $39, $81, $7f, $51, $fc, $d0, $3d, $81, $7a, $51, $fc, $80, $40, $4d
	.byte $81, $51, $fc, $60, $40, $51, $81, $51, $fc, $40, $35, $81, $72, $51, $fc, $00, $39, $81, $72, $51, $fc, $00, $3d, $81
	.byte $71, $51, $fe, $00, $40, $4d, $81, $71, $51, $fe, $00, $40, $51, $81, $00, $85, $91, $42
	.word @song1ch0loop
@song1ch1:
	.byte $47, $03, $82, $2e, $78, $83, $7f, $29, $78, $81, $7f, $30, $78, $81, $7f, $31, $78, $81, $77, $81, $76, $49, .lobyte(@env10)
	.byte .hibyte(@env10), $8b, $7f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $2d, $2e, $30, $78, $81, $7f, $28, $78, $81
	.byte $77, $81, $76, $85, $74, $49, .lobyte(@env15), .hibyte(@env15), $88, $3a, $a1
@song1ch1loop:
	.byte $85, $75, $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $0a, $81, $0d, $81, $11, $81, $15, $81, $19, $81, $1d, $81
	.byte $21, $81, $25, $81, $29, $81, $2d, $81, $31, $81, $35, $81
@song1ref334:
	.byte $39, $81, $3d, $81, $40, $4d, $81, $40, $51, $81, $35, $81, $39, $81, $3d, $81, $74, $40, $4d, $81, $73, $40, $51, $81
	.byte $72, $35, $81, $71
	.byte $41, $08
	.word @song1ref334
	.byte $00, $91, $42
	.word @song1ch1loop
@song1ch2:
	.byte $b3, $49, .lobyte(@env2), .hibyte(@env2), $82, $40, $0a, $a1
@song1ch2loop:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $0a, $d5, $00, $95, $91, $42
	.word @song1ch2loop
@song1ch3:
	.byte $b3, $a3
@song1ch3loop:
	.byte $ef, $91, $42
	.word @song1ch3loop
@song1ch4:
	.byte $b3, $a3
@song1ch4loop:
	.byte $ef, $91, $42
	.word @song1ch4loop
@song2ch0:
	.byte $46, $06, $87
@song2ch0loop:
@song2ref5:
	.byte $7f, $84, $0a, $81, $0d, $81, $11, $81, $15, $81, $19, $81, $1d, $81, $21, $81, $25, $81, $29, $81, $80, $0d, $81, $11
	.byte $81, $15, $81, $19, $81, $7a, $1d, $81, $21, $81, $25, $81
	.byte $41, $20
	.word @song2ref5
	.byte $7f
@song2ref45:
	.byte $84, $08, $81
@song2ref48:
	.byte $0d, $81, $11, $81, $14, $81, $19, $81, $1d, $81, $20, $81, $25, $81, $29, $81, $80
	.byte $41, $0e
	.word @song2ref48
	.byte $41, $12
	.word @song2ref45
	.byte $80
	.byte $41, $0e
	.word @song2ref48
@song2ref75:
	.byte $84, $06, $81, $0a, $81, $0d, $81, $11, $81, $16, $81, $19, $81, $1d, $81, $22, $81, $25, $81, $80, $0a, $81, $0d, $81
	.byte $11, $81, $16, $81, $7a, $19, $81, $1d, $81, $22, $81, $7f
	.byte $41, $20
	.word @song2ref75
@song2ref114:
	.byte $7f, $84, $05, $81, $09, $81, $0c, $81, $11, $81, $15, $81, $18, $81, $1d, $81, $21, $81, $24, $81, $80, $09, $81, $0c
	.byte $81, $11, $81, $15, $81, $7a, $18, $81, $1d, $81, $21, $81
	.byte $41, $20
	.word @song2ref114
	.byte $7f, $84
@song2ref155:
	.byte $0a, $81, $0d, $81, $11, $81, $15, $81, $19, $81, $1d, $71, $29, $7f, $21, $71, $29, $7f, $25, $72, $29, $7f, $29, $72
	.byte $29, $7f, $80, $0d, $72, $84, $29, $7f, $80, $11, $72, $84, $29, $7f, $80, $15, $72, $84, $29, $7f, $80, $19, $71, $84
	.byte $29, $7a, $80, $1d, $71, $84, $29, $7a, $80, $21, $71, $84, $29, $7a, $80, $25, $71, $84, $29, $7f
	.byte $41, $20
	.word @song2ref155
@song2ref226:
	.byte $7f, $08, $81, $0d, $81, $11, $81, $14, $81, $19, $81, $1d, $71, $29, $7f, $20, $71, $29, $7f, $25, $71, $29, $7f, $29
	.byte $71, $29, $7f, $80, $0d, $71, $84, $29, $7f, $80, $11, $71, $84, $29, $7f, $80, $14, $71, $84, $29, $7f, $80, $19, $71
	.byte $84, $29, $7a, $80, $1d, $71, $84, $29, $7a, $80, $20, $71, $84, $29, $7a, $80, $25, $71, $84, $29
	.byte $41, $20
	.word @song2ref226
@song2ref297:
	.byte $7f, $06, $81, $0a, $81, $0d, $81, $11, $81, $16, $81, $19, $71, $25, $7f, $1d, $71, $25, $7f, $22, $71, $25, $7f, $25
	.byte $71, $25, $7f, $80, $0a, $71, $84, $25, $7f, $80, $0d, $71, $84, $25, $7f, $80, $11, $71, $84, $25, $7f, $80, $16, $71
	.byte $84, $25, $7a, $80, $19, $71, $84, $25, $7a, $80, $1d, $71, $84, $25, $7a, $80, $22, $71, $84, $25
	.byte $41, $20
	.word @song2ref297
@song2ref368:
	.byte $7f, $05, $81, $09, $81, $0c, $81, $11, $81, $15, $81, $18, $71, $24, $7f, $1d, $71, $24, $7f, $21, $71, $24, $7f, $24
	.byte $71, $24, $7f, $80, $09, $71, $84, $24, $7f, $80, $0c, $71, $84, $24, $7f, $80, $11, $71, $84, $24, $7f, $80, $15, $71
	.byte $84, $24, $7a, $80, $18, $71, $84, $24, $7a, $80, $1d, $71, $84, $24, $7a, $80, $21, $71, $84, $24
	.byte $41, $20
	.word @song2ref368
	.byte $7f
	.byte $41, $20
	.word @song2ref155
	.byte $7f
	.byte $41, $20
	.word @song2ref155
	.byte $41, $20
	.word @song2ref226
	.byte $41, $20
	.word @song2ref226
	.byte $41, $20
	.word @song2ref297
	.byte $41, $20
	.word @song2ref297
	.byte $41, $20
	.word @song2ref368
	.byte $41, $20
	.word @song2ref368
	.byte $7f
	.byte $41, $20
	.word @song2ref155
	.byte $7f
	.byte $41, $20
	.word @song2ref155
	.byte $41, $20
	.word @song2ref226
	.byte $41, $20
	.word @song2ref226
	.byte $41, $20
	.word @song2ref297
	.byte $41, $20
	.word @song2ref297
	.byte $41, $20
	.word @song2ref368
	.byte $41, $20
	.word @song2ref368
	.byte $42
	.word @song2ch0loop
@song2ch1:
	.byte $8a, $22, $85
@song2ch1loop:
	.byte $7f
@song2ref499:
	.byte $29, $b9, $47, $03, $78, $8e, $27, $47, $01, $25, $7f, $8a, $24, $a5, $22, $85, $24, $89, $47, $02, $25, $81, $81, $1d
	.byte $bb, $b7, $22, $85
	.byte $41, $0f
	.word @song2ref499
@song2ref530:
	.byte $77, $80, $24, $81, $00, $89, $7f, $05, $81, $09, $81, $0c, $81, $11, $81, $15, $81, $18, $81, $78, $1d, $81, $75, $21
	.byte $81, $00, $85, $7f, $8a, $22, $85
	.byte $41, $12
	.word @song2ref499
	.byte $41, $0f
	.word @song2ref499
	.byte $41, $10
	.word @song2ref530
	.byte $1d, $81, $21, $81, $24, $81, $09, $81, $0c, $81, $11, $81, $7a, $8a
@song2ref584:
	.byte $16, $85, $7f, $21, $8d, $21, $85, $7a, $16, $85, $7f, $22, $8d, $22, $85, $7a, $16, $85, $7f, $24, $8d, $24, $85, $7a
	.byte $16, $85, $7f, $25, $8d, $25, $85, $7a, $14, $85, $7f, $20, $8d, $20, $85, $7a, $14, $85, $7f, $22, $8d, $22, $85, $7a
	.byte $14, $85, $7f, $24, $8d, $24, $85, $7a, $14, $85, $7f, $25, $8d, $25, $85, $7a, $12, $85, $7f, $21, $8d, $21, $85, $7a
	.byte $12, $85, $7f, $22, $8d, $22, $85, $7a, $12, $85, $7f, $24, $8d, $24, $85, $7a, $12, $85, $7f, $25, $8d, $25, $85, $7a
	.byte $11, $85, $7f, $21, $8d, $21, $85, $7a, $11, $85, $7f, $22, $8d, $22, $85, $7a, $11, $85, $7f, $24, $8d, $24, $85, $7a
	.byte $11, $85, $7f, $25, $8d, $25, $85, $7a
	.byte $41, $56
	.word @song2ref584
	.byte $7d, $24, $8d, $7b, $24, $8d, $78, $25, $8d, $7c, $22, $85, $42
	.word @song2ch1loop
@song2ch2:
	.byte $87
@song2ch2loop:
	.byte $84, $16, $bd, $16, $bd, $90, $14, $bd, $14, $bd, $12, $bd, $12, $bd, $11, $bd, $11, $bd
@song2ref750:
	.byte $0a, $85, $16, $85, $0a, $85, $16, $85, $0a, $85, $16, $85, $0a, $85, $16, $85
	.byte $41, $10
	.word @song2ref750
@song2ref769:
	.byte $08, $85, $14, $85, $08, $85, $14, $85, $08, $85, $14, $85, $08, $85, $14, $85
	.byte $41, $10
	.word @song2ref769
@song2ref788:
	.byte $06, $85, $12, $85, $06, $85, $12, $85, $06, $85, $12, $85, $06, $85, $12, $85
	.byte $41, $10
	.word @song2ref788
@song2ref807:
	.byte $05, $85, $11, $85, $05, $85, $11, $85, $05, $85, $11, $85, $05, $85, $11, $85
	.byte $41, $10
	.word @song2ref807
	.byte $41, $10
	.word @song2ref750
	.byte $41, $10
	.word @song2ref750
	.byte $41, $10
	.word @song2ref769
	.byte $41, $10
	.word @song2ref769
	.byte $41, $10
	.word @song2ref788
	.byte $41, $10
	.word @song2ref788
	.byte $41, $10
	.word @song2ref807
	.byte $41, $10
	.word @song2ref807
	.byte $41, $10
	.word @song2ref750
	.byte $41, $10
	.word @song2ref750
	.byte $41, $10
	.word @song2ref769
	.byte $41, $10
	.word @song2ref769
	.byte $41, $10
	.word @song2ref788
	.byte $41, $10
	.word @song2ref788
	.byte $41, $10
	.word @song2ref807
	.byte $41, $10
	.word @song2ref807
	.byte $42
	.word @song2ch2loop
@song2ch3:
	.byte $87
@song2ch3loop:
@song2ref879:
	.byte $86, $1f, $9d, $00, $9d, $bf, $bf, $bf, $bf, $bf, $bf, $ab, $88, $1f, $91
	.byte $41, $0d
	.word @song2ref879
	.byte $41, $0d
	.word @song2ref879
	.byte $41, $0d
	.word @song2ref879
	.byte $42
	.word @song2ch3loop
@song2ch4:
	.byte $87
@song2ch4loop:
@song2ref908:
	.byte $01, $81, $02, $81, $01, $81, $02, $81, $04, $81, $01, $81, $02, $81, $05, $81, $03, $81, $05, $81, $01, $81, $02, $81
	.byte $04, $81, $01, $81, $03, $81, $05, $81
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $41, $20
	.word @song2ref908
	.byte $42
	.word @song2ch4loop
