; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_ch2=music_data_ch2
.endif

music_data_ch2:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : finalboss
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_ch2
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env6,@env10,@env0 ; 00 : Low Floor Tom
	.word @env7,@env6,@env10,@env0 ; 01 : Maracas
	.word @env17,@env6,@env10,@env0 ; 02 : SnareLong
	.word @env1,@env6,@env10,@env0 ; 03 : Snare
	.word @env12,@env6,@env10,@env0 ; 04 : Low Floor Short
	.word @env9,@env6,@env10,@env0 ; 05 : Reverse Drum Buildup Thing
	.word @env4,@env6,@env10,@env0 ; 06 : Hi Hat
	.word @env2,@env6,@env11,@env0 ; 07 : Piano D
	.word @env5,@env6,@env10,@env0 ; 08 : Harpsichord
	.word @env13,@env6,@env10,@env0 ; 09 : Harpsichord 1
	.word @env16,@env6,@env11,@env0 ; 0a : Whistle
	.word @env15,@env6,@env11,@env0 ; 0b : Whistle 1
	.word @env3,@env6,@env14,@env0 ; 0c : Bass

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$ca,$c7,$c4,$c1,$c0,$00,$07
@env2:
	.byte $00,$c9,$c7,$c5,$c5,$c3,$c2,$03,$c1,$00,$08
@env3:
	.byte $00,$c2,$c6,$c8,$ca,$02,$c8,$c6,$c2,$00,$08
@env4:
	.byte $00,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@env5:
	.byte $00,$cd,$cc,$cb,$ca,$c9,$c8,$c6,$c4,$c1,$00,$09
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$cf,$c6,$00,$02
@env8:
	.byte $00,$cf,$c0,$00,$02
@env9:
	.byte $00,$c1,$02,$c2,$03,$c3,$02,$c4,$02,$c5,$02,$c6,$02,$c7,$c7,$c8,$c8,$c9,$c9,$ca,$ca,$cb,$cc,$cd,$ce,$cf,$00,$19
@env10:
	.byte $7f,$00,$00
@env11:
	.byte $c2,$7f,$00,$00
@env12:
	.byte $00,$cf,$ce,$cc,$ca,$c8,$c5,$c3,$c1,$c0,$00,$09
@env13:
	.byte $00,$ca,$c9,$c8,$c7,$c6,$c5,$c3,$c1,$00,$08
@env14:
	.byte $c1,$7f,$00,$00
@env15:
	.byte $00,$c5,$cb,$cf,$cd,$ca,$c8,$c7,$00,$07
@env16:
	.byte $00,$c5,$cb,$cf,$c8,$c6,$c5,$c4,$00,$07
@env17:
	.byte $00,$c6,$ca,$cf,$cf,$cd,$cc,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c6,$c5,$c3,$00,$10

@samples:

@song0ch0:
	.byte $46, $01
@song0ref3:
	.byte $8e
@song0ref4:
	.byte $35, $8f, $00, $31, $8f, $2e, $8f, $29, $8f, $25, $8f, $22, $8f, $1d, $8f, $19, $8f, $35, $8f, $00, $31, $8f, $2e, $8f
	.byte $29, $8f, $25, $8f, $22, $8f, $1d, $8f, $19, $8f
@song0ch0loop:
	.byte $36, $8f, $00, $31, $8f, $2e, $8f, $2a, $8f, $25, $8f, $22, $8f, $1e, $8f, $19, $8f
	.byte $41, $22
	.word @song0ref4
	.byte $35, $8f, $00, $31, $8f, $2e, $8f, $29, $8f, $25, $8f, $22, $8f, $1d, $8f, $19, $8f
@song0ref76:
	.byte $36, $8f, $00, $31, $8f, $2e, $8f, $2a, $8f, $25, $8f, $22, $8f, $1e, $8f, $19, $8f, $35, $8f, $00, $31, $8f, $2e, $8f
	.byte $29, $8f, $25, $8f, $22, $8f, $1d, $8f, $19
@song0ref109:
	.byte $8f, $29, $8f, $00, $25, $8f, $22, $8f, $1d, $8f, $19, $8f, $16, $8f, $11, $8f, $0d, $8f
@song0ref127:
	.byte $29, $8f, $00, $25, $8f, $22, $8f, $1d, $8f, $19, $8f, $16, $8f, $11, $8f, $0d, $8f, $2a, $8f, $00, $25, $8f, $22, $8f
	.byte $1e, $8f, $19, $8f, $16, $8f, $12, $8f, $0d
	.byte $41, $23
	.word @song0ref109
	.byte $41, $21
	.word @song0ref127
	.byte $8f, $29, $8f, $00, $25, $8f, $22, $8f, $1d, $8f, $19, $8f, $16, $8f, $11, $8f, $0d, $8f
	.byte $41, $22
	.word @song0ref4
	.byte $41, $22
	.word @song0ref76
	.byte $41, $22
	.word @song0ref4
	.byte $41, $22
	.word @song0ref76
	.byte $41, $22
	.word @song0ref4
	.byte $41, $22
	.word @song0ref76
	.byte $41, $22
	.word @song0ref4
	.byte $41, $22
	.word @song0ref76
	.byte $90
@song0ref209:
	.byte $2e, $b3, $00, $30, $8f, $31, $8f, $00, $8f, $36, $8f, $00, $8f, $2d, $8f, $00, $91, $35, $8f, $33, $8f, $31, $8f, $00
	.byte $8f, $2a, $8f, $2e, $8f, $2d
@song0ref239:
	.byte $8f, $00, $91, $30, $8f, $31, $8f, $33, $8f, $00, $8f, $30, $8f, $00, $8f, $31, $8f, $00, $91, $35, $8f, $33, $8f, $31
	.byte $8f, $30, $8f, $2e, $8f, $2d, $8f, $2a, $8f, $00, $91, $30, $8f, $31, $8f, $33, $8f, $00, $8f, $30, $8f, $00, $8f, $31
	.byte $8f, $00, $91, $2e, $8f, $2d, $8f, $2e, $8f, $00, $8f, $30, $8f, $31, $8f, $33, $8f, $00, $35, $8f, $36, $8f, $2d, $8f
	.byte $31, $8f, $33, $8f, $35, $8f, $2e, $8f, $30, $8f, $00, $31, $8f, $33, $8f, $36, $8f, $35, $8f, $34, $8f, $35, $8f, $00
	.byte $8f
	.byte $41, $1d
	.word @song0ref209
	.byte $30
	.byte $41, $61
	.word @song0ref239
	.byte $41, $7f
	.word @song0ref209
	.byte $41, $1d
	.word @song0ref209
	.byte $30
	.byte $41, $61
	.word @song0ref239
	.byte $92
	.byte $41, $7f
	.word @song0ref209
	.byte $41, $1d
	.word @song0ref209
	.byte $30
	.byte $41, $61
	.word @song0ref239
	.byte $41, $22
	.word @song0ref3
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $ff, $a3
@song0ch1loop:
	.byte $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $c9, $94, $22, $b3, $45, $d7, $00, $24, $a1, $45, $a1, $25, $c5, $45, $c5
	.byte $00, $2a, $c5, $45, $c5, $00, $29, $d7, $45, $d7, $00, $a5, $2e, $8f, $45, $8f, $30, $8f, $45, $8f, $31, $c5, $45, $c5
	.byte $00, $36, $c5, $45, $c5, $00, $35, $ff, $8d, $45, $ff, $8d, $00, $81, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $2e
	.byte $ff, $ff, $9d, $00, $81, $35, $ff, $8d, $00, $33, $ff, $8d, $00, $31, $ff, $ff, $9d, $00, $81, $38, $ff, $8d, $00, $36
	.byte $ff, $8d, $00, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3
@song0ref485:
	.byte $22, $c5, $00, $24, $c5, $25, $c5, $00, $2a, $c5, $21, $c5, $00, $29, $a1, $27, $a1, $25, $c5, $00, $22, $c5, $1e, $c5
	.byte $00, $27, $a1, $25, $a1, $24, $c5, $00, $1e, $c5, $1d, $c5, $00, $29, $a1, $27, $a1, $25, $c5, $00, $22, $a1, $21, $a1
	.byte $41, $30
	.word @song0ref485
@song0ref536:
	.byte $2e, $c5, $00, $30, $c5, $31, $c5, $00, $36, $c5, $2d, $c5, $00, $35, $a1, $33, $a1, $31, $c5, $00, $2e, $c5, $2a, $c5
	.byte $00, $33, $a1, $31, $a1, $30, $c5, $00, $2a, $c5, $29, $c5, $00, $35, $a1, $33, $a1, $31, $c5, $00, $2e, $a1, $2d, $a1
	.byte $96
	.byte $41, $30
	.word @song0ref536
	.byte $41, $30
	.word @song0ref536
	.byte $2e, $ff, $8d, $00, $ff, $91, $42
	.word @song0ch1loop
@song0ch2:
	.byte $98
@song0ref601:
	.byte $0a, $9d, $00, $83, $0a, $8f, $00, $a1, $0a, $8f, $00, $8f, $0a, $8f, $00, $91, $0a, $8f, $00, $8f, $0a, $8f, $00, $8f
	.byte $0a, $8f, $00, $8f, $0a, $8b, $00, $81
@song0ch2loop:
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
	.byte $41, $20
	.word @song0ref601
@song0ref679:
	.byte $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3, $ff, $ff, $a3
@song0ref703:
	.byte $0a, $ff, $8d, $00, $c9, $16, $c5, $09, $ff, $8d, $00, $c9, $15, $a1, $21, $a1, $06, $ff, $8d, $00, $c9, $12, $c5, $05
	.byte $ff, $8d, $00, $c9, $11, $a1, $1d, $a1
	.byte $41, $20
	.word @song0ref703
	.byte $41, $20
	.word @song0ref703
	.byte $41, $20
	.word @song0ref703
	.byte $41, $20
	.word @song0ref601
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ref750:
	.byte $84, $31, $a1, $00, $80, $24, $8f, $24, $8f, $84, $31, $a1, $80, $24, $81, $00, $8b, $24, $81, $00, $8b, $24, $81, $00
	.byte $8d, $24, $8f, $00, $8f, $86, $31, $8f, $80, $24, $81, $00, $95, $24, $81, $00, $9d, $24, $81, $00, $81
@song0ch3loop:
@song0ref796:
	.byte $84, $31, $c5, $00, $86, $31, $a1, $80, $24, $a1, $00, $91, $88, $24, $81, $00, $81, $24, $81, $00, $81, $24, $81, $00
	.byte $81, $24, $81, $00, $81, $24, $81, $00, $b3, $86, $2e, $8f, $80, $24, $8f
	.byte $41, $27
	.word @song0ref750
@song0ref838:
	.byte $84, $31, $c5, $00, $86, $31, $a1, $80, $24, $a1, $84, $31, $8f, $00, $86, $31, $87, $00, $85, $31, $8b, $00, $81, $88
	.byte $24, $8b, $00, $81, $24, $8b, $00, $93, $8c, $2e, $8f, $80, $24, $8f
@song0ref876:
	.byte $24, $93, $00, $8d, $24, $8f, $00, $8f, $86, $31, $8b, $84, $31, $81, $80, $24, $8f, $00, $8f, $86, $31, $8f, $00, $91
	.byte $31, $8f, $80, $24, $8f, $00, $8f, $86, $31, $8b, $84, $31, $81, $00, $8f, $80, $24, $8f, $86, $31, $8f, $80
	.byte $41, $24
	.word @song0ref876
	.byte $80
	.byte $41, $24
	.word @song0ref876
	.byte $80, $24, $93, $00, $8d, $24, $8f, $00, $8f, $86, $31, $8b, $84, $31, $81, $80, $24, $8f, $00, $8f, $86, $31, $8f, $8a
	.byte $31, $ff, $8d, $00
	.byte $41, $27
	.word @song0ref750
	.byte $41, $21
	.word @song0ref796
	.byte $41, $27
	.word @song0ref750
	.byte $41, $1e
	.word @song0ref838
	.byte $41, $27
	.word @song0ref750
	.byte $41, $21
	.word @song0ref796
	.byte $41, $27
	.word @song0ref750
	.byte $84, $31, $c5, $00, $86, $31, $a1, $80, $24, $a1
@song0ref988:
	.byte $8a, $31, $ff, $8d, $00, $84, $31, $a3, $80, $24, $8f, $00, $93
@song0ref1001:
	.byte $86, $31, $87, $84, $31, $81, $82, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $9f, $40, $4e
	.byte $81, $00, $8b, $40, $4e, $81, $80, $24, $8b, $82, $40, $4e, $81, $00, $8f, $86, $31, $87, $84, $31, $81, $82, $40, $4e
	.byte $81, $80, $24, $8b, $82, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b, $83, $80, $24, $8d, $82, $40, $4e, $81, $00
	.byte $8b, $40, $4e, $81, $80, $24, $8b, $82, $40, $4e, $81, $00, $8f
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $86, $31, $87, $84, $31, $81, $82, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b
	.byte $41, $45
	.word @song0ref988
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $41, $3b
	.word @song0ref1001
	.byte $86, $31, $87, $84, $31, $81, $82, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b, $40, $4e, $81, $00, $8b, $8a, $31
	.byte $ff, $8d, $00
	.byte $41, $27
	.word @song0ref750
	.byte $41, $21
	.word @song0ref796
	.byte $41, $27
	.word @song0ref750
	.byte $41, $1e
	.word @song0ref838
	.byte $41, $27
	.word @song0ref750
	.byte $41, $21
	.word @song0ref796
	.byte $41, $27
	.word @song0ref750
	.byte $84, $31, $c5, $00, $86, $31, $a1, $80, $24, $a1, $8a, $31, $ff, $8d, $00
	.byte $41, $27
	.word @song0ref750
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $ff, $a3
@song0ch4loop:
	.byte $41, $18
	.word @song0ref679
	.byte $41, $18
	.word @song0ref679
	.byte $41, $18
	.word @song0ref679
	.byte $41, $18
	.word @song0ref679
	.byte $41, $18
	.word @song0ref679
	.byte $42
	.word @song0ch4loop
