; Copyright (C) 2024 iProgramInCpp.

; This is music data that only contains one song that plays nothing.
; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_blank=music_data_blank
.endif

music_data_blank:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : blank
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_blank
.global FAMISTUDIO_DPCM_PTR

@instruments:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$7f,$00,$01
@env2:
	.byte $7f,$00,$00

@samples:

@song0ch0:
	.byte $46, $0a
@song0ch0loop:
	.byte $9f, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $9f, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $9f, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $9f, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $9f, $42
	.word @song0ch4loop
