; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_prologue=music_data_prologue
.endif

music_data_prologue:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : intro_loop
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : bridge_oneshot
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_prologue
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env6,@env0 ; 00 : Piano
	.word @env3,@env2,@env7,@env0 ; 01 : Piano 1
	.word @env4,@env2,@env6,@env0 ; 02 : BassPiano
	.word @env8,@env2,@env5,@env0 ; 03 : Percussion
	.word @env9,@env2,@env5,@env0 ; 04 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cc,$ce,$cf,$cd,$cb,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0e
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $00,$cf,$cf,$ce,$cc,$ca,$c8,$c7,$c5,$c4,$c3,$c2,$c1,$00,$0c
@env4:
	.byte $00,$ce,$cd,$cc,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c0,$00,$0d
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c2,$7f,$00,$00
@env7:
	.byte $c1,$7f,$00,$00
@env8:
	.byte $00,$cf,$cb,$c8,$c5,$c3,$c2,$c1,$c0,$00,$08
@env9:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$02,$cb,$02,$ca,$02,$c9,$04,$c8,$03,$c7,$04,$c6,$06,$c5,$05,$c4,$06,$c3,$05,$c2,$07,$c1,$16,$c0,$00,$1f

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $80, $29, $bd, $30, $bd, $37, $bd, $35, $bd, $48, $bf, $3c, $ff, $bd, $48, $ff, $00, $fd
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref23:
	.byte $ff, $27, $bd, $30, $bd, $48, $37, $bd, $35, $fd, $3c, $bd, $48, $ff, $ff, $48, $00, $ff, $fd, $48, $29, $bd, $30, $bd
	.byte $37, $bd, $35, $bd, $48, $bf, $3c, $ff, $bd, $48, $ff, $00, $fd, $48
	.byte $41, $1f
	.word @song0ref23
	.byte $48
	.byte $41, $1f
	.word @song0ref23
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $ff, $ff, $ff, $ff, $82, $39, $bd, $00, $bd
@song0ch1loop:
	.byte $37, $bd, $35, $bd, $33, $bd, $00, $bd, $ff, $ff, $ff, $ff, $35, $bd, $37, $bd, $39, $bd, $3a, $bd, $3c, $9d, $00, $ff
	.byte $dd, $ff, $ff, $ff, $ff, $40, $4d, $fd, $3f, $9d, $00, $dd, $ff, $ff, $ff, $ff, $ff, $3e, $bd, $3a, $bd, $3c, $9d, $00
	.byte $ff, $dd, $ff, $ff, $ff, $35, $bd, $37, $bd, $39, $bd, $3a, $bd, $37, $9d, $00, $dd, $ff, $ff, $ff, $ff, $ff, $35, $bd
	.byte $00, $bd, $35, $9d, $00, $ff, $dd, $ff, $ff, $ff, $39, $bd, $00, $bd, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song0ch2loop:
@song0ref178:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $15
	.word @song0ref178
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song0ch3loop:
	.byte $41, $15
	.word @song0ref178
	.byte $41, $15
	.word @song0ref178
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song0ch4loop:
	.byte $41, $15
	.word @song0ref178
	.byte $41, $15
	.word @song0ref178
	.byte $42
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song1ref6:
	.byte $29, $8b, $30, $8b, $35, $8b, $37, $8b, $29, $8b, $30, $8b, $35, $8b, $37, $8b
	.byte $41, $10
	.word @song1ref6
	.byte $48
@song1ref26:
	.byte $2c, $8b, $30, $8b, $35, $8b, $37, $8b, $2c, $8b, $30, $8b, $35, $8b, $37, $8b
	.byte $41, $10
	.word @song1ref26
	.byte $48
@song1ref46:
	.byte $2e, $8b, $30, $8b, $35, $8b, $37, $8b, $2e, $8b, $30, $8b, $35, $8b, $37, $8b
	.byte $41, $10
	.word @song1ref46
	.byte $48
@song1ref66:
	.byte $2f, $8b, $30, $8b, $35, $8b, $37, $8b, $2f, $8b, $30, $8b, $35, $8b, $37, $8b
	.byte $41, $10
	.word @song1ref66
	.byte $48, $b7, $00, $ff, $a5, $48, $ff, $df, $48, $40, $54, $fb, $00
@song1ref98:
	.byte $df, $48, $ff, $df, $48, $ff, $df, $48, $ff, $df, $48, $ff, $df, $48, $ff
	.byte $41, $09
	.word @song1ref98
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
@song1ref120:
	.byte $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
	.byte $41, $0a
	.word @song1ref120
	.byte $41, $0a
	.word @song1ref120
	.byte $ff, $df, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $84, $1d, $df, $00, $8b, $1d, $df, $00, $8b, $20, $df, $00, $8b, $20, $df, $00, $8b, $1d, $a7, $00, $8b, $1d, $a7, $00
	.byte $8b, $1d, $a7, $00, $8b, $1d, $a7, $00, $8b, $23, $a7, $00, $8b, $23, $a7, $00, $8b, $23, $a7, $00, $8b, $23, $a7, $00
	.byte $8b
	.byte $41, $0a
	.word @song1ref120
	.byte $41, $0a
	.word @song1ref120
	.byte $ff, $df, $ff, $df, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $86
@song1ref206:
	.byte $34, $8b, $00, $8b, $32, $8b, $00, $a7, $32, $8b, $00, $8b
	.byte $41, $0c
	.word @song1ref206
	.byte $41, $0c
	.word @song1ref206
	.byte $41, $0c
	.word @song1ref206
@song1ref227:
	.byte $34, $8b, $00, $8b, $32, $8b, $00, $8b, $34, $8b, $00, $8b, $32, $8b, $00, $8b
	.byte $41, $10
	.word @song1ref227
	.byte $41, $10
	.word @song1ref227
	.byte $34, $8b, $00, $8b, $32, $8b, $32, $8b, $34, $8b, $00, $8b, $88, $32, $99, $ff, $c3, $00, $99
	.byte $41, $0a
	.word @song1ref120
	.byte $41, $0a
	.word @song1ref120
	.byte $ff, $df, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $41, $0a
	.word @song1ref120
	.byte $41, $0a
	.word @song1ref120
	.byte $41, $0a
	.word @song1ref120
	.byte $ff, $df, $42
	.word @song1ch4loop
