; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_ch0=music_data_ch0
.endif

music_data_ch0:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : 0
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 225,187
; 01 : 1
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 266,221

.export music_data_ch0
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env2,@env4,@env0 ; 00 : Marimba
	.word @env6,@env5,@env4,@env0 ; 01 : Piano
	.word @env1,@env2,@env3,@env0 ; 02 : DPCM
	.word @env6,@env2,@env4,@env0 ; 03 : Piano without octave
	.word @env7,@env2,@env3,@env0 ; 04 : Cymbal

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $b4,$b4,$c0,$00,$02
@env6:
	.byte $00,$cb,$c9,$c9,$c8,$c7,$c7,$c6,$02,$c5,$03,$c4,$04,$c3,$03,$c2,$04,$c1,$06,$c0,$00,$13
@env7:
	.byte $00,$c6,$03,$c5,$07,$c4,$07,$c3,$08,$c2,$07,$c1,$00,$0b
@env8:
	.byte $00,$c4,$c7,$02,$c5,$c4,$c3,$03,$c2,$02,$c1,$00,$0a

@samples:

@song0ch0:
	.byte $46, $06, $80, $1d, $f1
@song0ch0loop:
	.byte $1b, $f5, $1d, $ed, $1b, $ed, $1d, $f5, $1b, $ed, $1d, $f5, $42
	.word @song0ch0loop
@song0ch1:
	.byte $87, $80, $24, $85, $2b, $85, $29, $8d, $30, $a9, $39, $8d, $37, $85, $35, $85
@song0ch1loop:
	.byte $33
@song0ref40:
	.byte $85, $24, $85, $2b, $85, $29, $8d, $30, $ad, $35, $85, $37, $85, $39, $85, $3a, $85, $3c
	.byte $41, $08
	.word @song0ref40
	.byte $b5, $40, $4d, $8d, $3f
	.byte $41, $08
	.word @song0ref40
	.byte $b5, $3e, $85, $3a, $85, $3c
	.byte $41, $11
	.word @song0ref40
	.byte $37
	.byte $41, $08
	.word @song0ref40
	.byte $b5, $35, $8d, $35
	.byte $41, $09
	.word @song0ref40
	.byte $39, $8d, $37, $85, $35, $85, $42
	.word @song0ch1loop
@song0ch2:
	.byte $f3
@song0ch2loop:
	.byte $f7, $ef, $ef, $f7, $ef, $f7, $42
	.word @song0ch2loop
@song0ch3:
	.byte $f3
@song0ch3loop:
	.byte $f7, $ef, $ef, $f7, $ef, $f7, $42
	.word @song0ch3loop
@song0ch4:
	.byte $f3
@song0ch4loop:
	.byte $f7, $ef, $ef, $f7, $ef, $f7, $42
	.word @song0ch4loop
@song1ch0:
	.byte $46, $03, $99, $82
@song1ref5:
	.byte $29, $85, $73, $29, $85, $7f, $29, $85, $73, $29, $85, $7f
	.byte $41, $08
	.word @song1ref5
@song1ref20:
	.byte $7f, $2c, $85, $73, $2c, $85, $7f, $2c, $85, $73, $2c, $85
	.byte $41, $08
	.word @song1ref20
@song1ref35:
	.byte $7f, $2e, $85, $73, $2e, $85, $7f, $2e, $85, $73, $2e, $85
	.byte $41, $08
	.word @song1ref35
@song1ref50:
	.byte $7f, $80, $2f, $85, $73, $82, $2f, $85, $7f, $80, $2f, $85, $73, $82, $2f, $85
	.byte $41, $08
	.word @song1ref50
	.byte $8f, $00, $ed
@song1ch0loop:
	.byte $91, $42
	.word @song1ch0loop
@song1ch1:
	.byte $99, $7a, $86
@song1ref80:
	.byte $35, $81, $30, $81, $7c, $35, $81, $37, $81, $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $7a
	.byte $41, $08
	.word @song1ref80
	.byte $73, $35, $81, $37, $81, $71, $35, $81, $37, $81, $00, $ed
@song1ch1loop:
	.byte $91, $42
	.word @song1ch1loop
@song1ch2:
	.byte $99, $84, $05, $bd, $08, $bd, $03, $bd, $0b, $bd, $00, $fd
@song1ch2loop:
	.byte $91, $42
	.word @song1ch2loop
@song1ch3:
	.byte $71, $84, $14, $72, $15, $16, $17, $73, $18, $19, $1a, $75, $1b, $1c, $77, $1d, $1e, $79, $1f, $7d, $20, $7f, $88
@song1ref206:
	.byte $19, $14, $00, $81, $20, $8d, $20, $85
	.byte $41, $08
	.word @song1ref206
	.byte $41, $08
	.word @song1ref206
	.byte $41, $08
	.word @song1ref206
@song1ref223:
	.byte $19, $78, $14, $83, $20, $81, $75, $14, $81, $7f, $19, $78, $14, $83, $20, $81, $75, $14, $81, $7f
	.byte $41, $0e
	.word @song1ref223
	.byte $7f
	.byte $41, $0e
	.word @song1ref223
	.byte $7f
	.byte $41, $08
	.word @song1ref223
	.byte $1a, $1b, $1c, $1d, $1e, $1f, $20, $21, $23, $fb
@song1ch3loop:
	.byte $91, $42
	.word @song1ch3loop
@song1ch4:
	.byte $99, $ff, $ff, $ff
@song1ch4loop:
	.byte $91, $42
	.word @song1ch4loop
