; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Project uses delayed notes or cuts, you must set FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_ch1=music_data_ch1
.endif

music_data_ch1:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : New song
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 184,153

.export music_data_ch1
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env18,@env22,@env0 ; 00 : noise burst
	.word @env20,@env18,@env24,@env0 ; 01 : soft piano
	.word @env9,@env18,@env25,@env0 ; 02 : soft pluck
	.word @env14,@env18,@env22,@env23 ; 03 : lead up
	.word @env14,@env18,@env22,@env15 ; 04 : lead
	.word @env14,@env18,@env22,@env16 ; 05 : lead down
	.word @env32,@env27,@env1,@env0 ; 06 : noise snare
	.word @env26,@env2,@env22,@env0 ; 07 : cymb wash
	.word @env21,@env18,@env22,@env0 ; 08 : noise kick
	.word @env12,@env10,@env6,@env0 ; 09 : synth down 027
	.word @env31,@env10,@env6,@env0 ; 0a : synth up 027
	.word @env29,@env2,@env22,@env0 ; 0b : rev cymb
	.word @env12,@env30,@env6,@env0 ; 0c : synth down 025
	.word @env31,@env30,@env6,@env0 ; 0d : synth up 025
	.word @env12,@env11,@env6,@env0 ; 0e : synth down 03A
	.word @env31,@env19,@env6,@env0 ; 0f : synth up 039
	.word @env31,@env11,@env6,@env0 ; 10 : synth up 03A
	.word @env12,@env17,@env6,@env0 ; 11 : synth down 029
	.word @env12,@env19,@env6,@env0 ; 12 : synth down 039
	.word @env31,@env8,@env6,@env0 ; 13 : synth up 07E
	.word @env12,@env4,@env6,@env0 ; 14 : synth down 05E
	.word @env31,@env4,@env6,@env0 ; 15 : synth up 05E
	.word @env31,@env17,@env6,@env0 ; 16 : synth up 029
	.word @env12,@env8,@env6,@env0 ; 17 : synth down 07E
	.word @env7,@env18,@env24,@env28 ; 18 : piano lead
	.word @env13,@env18,@env22,@env5 ; 19 : plain tri

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c0,$00,$01
@env2:
	.byte $c2,$c1,$c2,$00,$00
@env3:
	.byte $00,$cf,$c8,$c4,$c2,$c1,$07,$c0,$00,$07
@env4:
	.byte $ce,$ce,$c5,$c5,$c0,$c0,$00,$00
@env5:
	.byte $00,$c0,$08,$c1,$03,$c0,$03,$bf,$03,$c0,$c0,$c0,$c1,$c2,$03,$c1,$c0,$bf,$be,$03,$bf,$c0,$00,$0b
@env6:
	.byte $c0,$c0,$c1,$c1,$00,$00
@env7:
	.byte $00,$c6,$ce,$cf,$cd,$cc,$ca,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$03,$c4,$03,$c3,$05,$c2,$09,$c1,$0b,$c0,$00,$19
@env8:
	.byte $ce,$ce,$c7,$c7,$c0,$c0,$00,$00
@env9:
	.byte $00,$cf,$cc,$c9,$c7,$c6,$c5,$c5,$c4,$02,$c3,$07,$c2,$c1,$00,$0d
@env10:
	.byte $c7,$c7,$c2,$c2,$c0,$c0,$00,$00
@env11:
	.byte $ca,$ca,$c3,$c3,$c0,$c0,$00,$00
@env12:
	.byte $00,$cc,$ce,$cf,$04,$ce,$02,$cd,$cc,$cb,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c5,$c5,$c4,$c3,$00,$15
@env13:
	.byte $00,$cf,$7f,$00,$02
@env14:
	.byte $00,$cf,$cf,$ce,$cd,$cc,$cb,$02,$ca,$04,$c9,$04,$c8,$04,$c7,$07,$c6,$0a,$c5,$00,$12
@env15:
	.byte $00,$c0,$09,$c1,$07,$c0,$07,$bf,$07,$c0,$06,$c0,$00,$03
@env16:
	.byte $00,$bc,$be,$bf,$c0,$06,$c1,$07,$c0,$07,$bf,$07,$c0,$06,$c0,$00,$06
@env17:
	.byte $c9,$c9,$c2,$c2,$c0,$c0,$00,$00
@env18:
	.byte $c0,$7f,$00,$01
@env19:
	.byte $c9,$c9,$c3,$c3,$c0,$c0,$00,$00
@env20:
	.byte $00,$c6,$ce,$cf,$cd,$cc,$c9,$c8,$c7,$03,$c6,$02,$c5,$03,$c4,$c4,$c3,$02,$c2,$02,$c1,$05,$c0,$00,$16
@env21:
	.byte $00,$cf,$c0,$00,$02
@env22:
	.byte $7f,$00,$00
@env23:
	.byte $00,$c4,$c2,$c1,$c0,$06,$c1,$07,$c0,$07,$bf,$07,$c0,$06,$c0,$00,$06
@env24:
	.byte $c2,$7f,$00,$00
@env25:
	.byte $c1,$7f,$00,$00
@env26:
	.byte $00,$cf,$05,$ce,$04,$cd,$02,$cc,$02,$cb,$02,$ca,$02,$c9,$02,$c8,$02,$c7,$04,$c6,$03,$c5,$02,$c4,$04,$c3,$06,$c2,$06,$c1,$00,$1d
@env27:
	.byte $c8,$cb,$c9,$cb,$ca,$cb,$ca,$cb,$cc,$cb,$cc,$cb,$00,$09
@env28:
	.byte $00,$c0,$0b,$c1,$c2,$02,$c1,$c0,$bf,$be,$02,$bf,$c0,$00,$03
@env29:
	.byte $00,$c1,$03,$c2,$05,$c3,$05,$c4,$05,$c5,$04,$c6,$03,$c7,$04,$c8,$02,$c9,$c9,$ca,$ca,$cb,$cb,$cc,$cc,$cd,$ce,$cf,$00,$1b
@env30:
	.byte $c5,$c5,$c2,$c2,$c0,$c0,$00,$00
@env31:
	.byte $00,$c5,$c6,$c7,$c8,$c9,$cc,$ce,$cf,$05,$ce,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c8,$c7,$00,$13
@env32:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$c9,$c7,$c6,$c4,$c3,$c3,$c2,$05,$c1,$03,$c0,$00,$12

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0f,$40 ; 00 kick30.dmc (Pitch:15)
	.byte $07+.lobyte(FAMISTUDIO_DPCM_PTR),$3b,$0f,$40 ; 01 snare.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03, $83, $75, $82
@song0ref6:
	.byte $35, $81, $72, $30, $81, $71, $2e, $81, $72, $29, $81, $75, $35, $81, $72, $30, $81, $71, $2e, $81, $72, $29, $81, $75
	.byte $41, $0e
	.word @song0ref6
@song0ref33:
	.byte $73, $29, $81, $76, $35, $81, $73, $30, $81, $72, $2e, $81, $73, $29, $81, $76, $35, $81, $73, $30, $81, $72, $2e, $81
	.byte $41, $10
	.word @song0ref33
@song0ch0loop:
	.byte $41, $10
	.word @song0ref33
	.byte $41, $10
	.word @song0ref33
	.byte $41, $10
	.word @song0ref33
	.byte $41, $10
	.word @song0ref33
	.byte $7a, $84
@song0ref75:
	.byte $1d, $81, $1f, $81, $79, $21, $81, $22, $81
@song0ref84:
	.byte $1d, $81, $1f, $81, $78, $21, $81, $22, $81, $1d, $81, $1f, $81, $77, $21, $81, $22, $81, $1d, $81, $1f, $81, $76, $21
	.byte $81, $22, $81, $78, $1d, $81, $1f, $81, $77, $21, $81, $22, $81
@song0ref121:
	.byte $79, $1d, $81, $1f, $81, $78, $21, $81, $22, $81, $7a, $1d, $81, $1f, $81, $79, $21, $81, $22, $81, $7b, $1d, $81, $1f
	.byte $81, $7a, $21, $81, $22, $81
	.byte $41, $40
	.word @song0ref75
	.byte $7b, $1d, $81, $1f, $81, $7a, $21, $81, $22, $81
	.byte $41, $18
	.word @song0ref75
	.byte $41, $18
	.word @song0ref121
	.byte $7c, $1d, $81, $1f, $81, $7b, $21, $81, $22, $81, $1d, $81, $1f, $81, $7a, $21, $81, $22, $81
	.byte $41, $18
	.word @song0ref75
	.byte $41, $18
	.word @song0ref121
@song0ref195:
	.byte $7c, $1d, $81, $1f, $81, $7b, $21, $81, $22, $81, $7a, $82, $15, $85, $84, $21, $81, $22, $81, $1d, $81, $1f, $81, $7b
	.byte $82, $16, $85, $79, $84
	.byte $41, $10
	.word @song0ref84
	.byte $79, $1d, $81, $1f, $81, $7a, $82, $18, $85, $84, $1d, $81, $1f, $81, $79, $82, $1a, $85, $7b, $84, $1d, $81, $1f, $81
	.byte $7a, $21, $81, $22, $81
	.byte $41, $14
	.word @song0ref195
	.byte $79, $84
	.byte $41, $10
	.word @song0ref84
	.byte $79, $1d, $81, $1f, $81, $7a, $82, $18, $85, $84, $1d, $81, $1f, $81, $79, $82, $16, $85, $7b, $84, $1d, $81, $1f, $81
	.byte $7a, $21, $81, $22, $81, $7c, $1d, $81, $1f, $81, $7b, $21
@song0ref300:
	.byte $81, $22
@song0ref302:
	.byte $81
@song0ref303:
	.byte $82, $19, $85, $7a, $84
@song0ref308:
	.byte $20, $81, $22, $81, $1d, $81, $1f, $81, $79, $20, $81, $22, $81
@song0ref321:
	.byte $1d, $81, $1f, $81, $78, $20, $81, $22, $81, $1d, $81, $1f, $81, $77, $20, $81, $22, $81, $79, $1d, $81, $1f, $81, $7a
	.byte $82, $18, $85, $84, $1d, $81, $1f, $81, $7b, $82, $19, $85, $84, $1d, $81, $1f, $81, $7a, $20, $81, $22, $81, $7c, $82
	.byte $18, $85, $7b, $84, $20, $81, $22, $81, $82, $16, $85, $7a, $84, $20, $81, $22, $81, $1d, $81, $1f, $81, $82, $14, $85
	.byte $79, $84
	.byte $41, $14
	.word @song0ref321
@song0ref398:
	.byte $7b, $82, $13, $85, $7a, $84, $1d, $81, $1f, $81, $82, $14, $85, $7b, $84, $1d, $81, $1f, $81, $7a, $20, $81, $22, $81
	.byte $7c, $1d, $81, $1f, $81, $7b, $20
	.byte $41, $47
	.word @song0ref300
	.byte $79, $84
	.byte $41, $14
	.word @song0ref321
	.byte $41, $15
	.word @song0ref398
	.byte $81, $22, $81, $1d, $81, $1f, $81, $7a
	.byte $41, $20
	.word @song0ref308
@song0ref451:
	.byte $78, $20, $81, $22, $81, $7a, $1d, $81, $1f, $81, $79, $20, $81, $22, $81, $7b, $1d, $81, $1f, $81, $7a, $20, $81, $22
	.byte $81, $7c, $1d, $81, $1f, $81, $7b, $20, $81, $22, $81, $1d, $81, $1f, $81, $7a
	.byte $41, $20
	.word @song0ref308
	.byte $41, $20
	.word @song0ref451
	.byte $7a
	.byte $41, $20
	.word @song0ref308
	.byte $41, $20
	.word @song0ref451
	.byte $7a
	.byte $41, $20
	.word @song0ref308
	.byte $41, $1c
	.word @song0ref451
@song0ref511:
	.byte $20, $81, $22, $81, $7a, $24, $81, $25, $81, $20, $81, $22, $81, $79, $24, $81, $25, $81, $20, $81, $22, $81, $78, $24
	.byte $81, $25, $81, $20, $81, $22, $81, $77, $24, $81, $25, $81, $79, $20, $81, $22, $81, $78, $24, $81, $25, $81, $7a, $20
	.byte $81, $22, $81, $79, $24, $81, $25, $81, $7b, $20, $81, $22, $81, $7a, $24, $81, $25, $81, $7c, $20, $81, $22, $81, $7b
	.byte $24, $81, $25, $81
	.byte $41, $40
	.word @song0ref511
	.byte $41, $40
	.word @song0ref511
	.byte $41, $40
	.word @song0ref511
	.byte $41, $3a
	.word @song0ref303
@song0ref599:
	.byte $7a, $84, $22, $81, $24, $81, $1d, $81, $20, $81, $82, $14, $85, $79, $84, $1d, $81, $20, $81, $78, $22, $81, $24, $81
	.byte $1d, $81, $20, $81, $77, $22, $81, $24, $81, $79, $1d, $81, $20, $81, $7b, $82, $13, $85, $7a, $84, $1d, $81, $20, $81
	.byte $82, $14, $85, $7b, $84, $1d, $81, $20, $81, $7a, $22, $81, $24, $81, $7c, $1d, $81, $20, $81, $7b, $22, $81, $24
	.byte $41, $3b
	.word @song0ref302
	.byte $41, $35
	.word @song0ref599
	.byte $81, $1d, $81, $1f, $81, $7a
	.byte $41, $20
	.word @song0ref308
	.byte $41, $20
	.word @song0ref451
	.byte $7a
	.byte $41, $20
	.word @song0ref308
	.byte $41, $20
	.word @song0ref451
	.byte $7a
	.byte $41, $20
	.word @song0ref308
	.byte $41, $20
	.word @song0ref451
	.byte $7a
	.byte $41, $20
	.word @song0ref308
	.byte $41, $1c
	.word @song0ref451
@song0ref709:
	.byte $79, $9c, $18, $8d, $78, $18, $8d, $77, $18, $89, $a0, $18, $81, $76, $18, $81, $47, $01, $77, $18, $83, $47, $00, $78
	.byte $18, $83, $79, $a4, $18, $8d, $78, $18, $8d, $77, $18, $89, $9e, $18, $81, $76, $18, $81, $47, $01, $77, $18, $83, $47
	.byte $00, $78, $18, $83
	.byte $41, $1c
	.word @song0ref709
	.byte $41, $1c
	.word @song0ref709
	.byte $41, $1c
	.word @song0ref709
	.byte $79, $92, $1b, $8d
@song0ref774:
	.byte $78
@song0ref775:
	.byte $1b, $8d, $77, $1b, $89, $94, $1b, $81, $76, $1b, $81, $47, $01, $77, $1b, $83, $47, $00, $78, $1b, $83, $79, $92, $1b
	.byte $8d, $78, $98, $1b, $8d, $77, $1b, $89, $9a, $1b, $81, $76, $1b, $81, $47, $01, $77, $1b, $83, $47, $00, $78, $1b, $83
	.byte $79, $a2, $1b, $8d, $78, $1b, $8d, $77, $1b, $89, $ac, $1b, $81, $76, $1b, $81, $47, $01, $77, $1b, $83, $47, $00, $78
	.byte $1b, $83, $79, $a2, $1b, $8d, $78, $92
	.byte $41, $0e
	.word @song0ref775
	.byte $41, $2a
	.word @song0ref774
	.byte $78, $92, $1b, $8d, $77, $1b, $89, $94, $1b, $81, $76, $1b, $81, $47, $01, $77, $1b, $83, $47, $00, $78, $1b, $83, $7b
	.byte $82
@song0ref886:
	.byte $35, $73, $29, $78, $30, $73, $35, $77, $2e, $73, $30, $78, $29, $73, $2e, $7c, $35, $73, $29, $79, $30, $73, $35, $78
	.byte $2e, $73, $30, $79, $29, $73, $2e, $7b, $35, $73, $29, $78, $30, $73, $35, $77, $2e, $73, $30, $78, $29, $73, $2e, $7a
	.byte $35, $73, $29, $77, $30, $73, $35, $76, $2e, $73, $30, $77, $29, $73, $2e, $7b
	.byte $41, $20
	.word @song0ref886
	.byte $7b
	.byte $41, $20
	.word @song0ref886
	.byte $7b
	.byte $41, $20
	.word @song0ref886
	.byte $7b
	.byte $41, $20
	.word @song0ref886
	.byte $7b
	.byte $41, $20
	.word @song0ref886
	.byte $7b
	.byte $41, $20
	.word @song0ref886
	.byte $7b
	.byte $41, $20
	.word @song0ref886
	.byte $77
@song0ref978:
	.byte $35, $81, $74, $30, $81, $73, $2e, $81, $74, $29, $81, $78, $35, $81, $75, $30, $81, $74, $2e, $81, $75, $29, $81
@song0ref1001:
	.byte $78, $35, $81, $75, $30, $81, $74, $2e, $81, $75, $29, $81, $77, $35, $81, $74, $30, $81, $73, $2e, $81, $74, $29, $81
	.byte $72, $29, $81, $75
	.byte $41, $0e
	.word @song0ref6
	.byte $41, $10
	.word @song0ref33
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $77, $82
	.byte $41, $20
	.word @song0ref978
	.byte $79
@song0ref1044:
	.byte $35, $81, $76, $30, $81, $75, $2e, $81, $76
@song0ref1053:
	.byte $29, $81, $7a, $35, $81, $77, $30, $81, $76, $2e, $81, $77, $29, $81
@song0ref1067:
	.byte $79, $35, $81, $76, $30, $81, $75, $2e, $81, $76, $29, $81, $78, $35, $81, $75, $30, $81, $74, $2e, $81, $75, $29, $81
@song0ch1loop:
@song0ref1092:
	.byte $7a, $35, $81, $77, $30, $81, $76, $2e, $81, $77, $29, $81, $7b, $35, $81, $78, $30, $81, $77, $2e, $81, $78
	.byte $41, $12
	.word @song0ref1053
	.byte $41, $0e
	.word @song0ref1092
	.byte $78
	.byte $41, $12
	.word @song0ref1053
	.byte $41, $0e
	.word @song0ref1092
	.byte $78
	.byte $41, $12
	.word @song0ref1053
	.byte $41, $0e
	.word @song0ref1092
	.byte $78
	.byte $41, $12
	.word @song0ref1053
	.byte $7a, $35, $81, $77, $30, $81, $76, $2e, $81, $77
	.byte $41, $12
	.word @song0ref1053
	.byte $41, $10
	.word @song0ref1067
	.byte $41, $10
	.word @song0ref1001
	.byte $77, $35, $81, $73, $30, $81, $72, $2e, $81, $73, $29, $81, $7d, $4f, $02, $88, $29, $8d, $7a, $29, $81, $78, $8a, $24
	.byte $74, $81, $7a, $86, $2b, $77, $81, $7b, $2d, $97, $71, $81, $77, $88, $2d, $81, $78, $86, $2e, $74, $81, $7c, $30, $91
	.byte $7a, $88, $30, $32, $83, $7b, $8a, $30, $79, $81, $7c, $2e, $83, $7a, $81, $79, $88, $2d, $85, $7a, $8a, $2b, $85, $77
	.byte $88, $29, $81, $78, $86, $2b, $76, $81, $7c, $4f, $02, $2d, $81, $7b, $81, $78, $81, $7a, $88, $2d, $81, $79, $86, $2e
	.byte $76, $81, $7a, $30, $95, $79, $87, $78, $87, $77, $87, $76, $83, $75, $83, $77, $88, $29, $81, $78, $86, $2b, $81, $79
	.byte $88, $2d, $81, $7a, $2e, $76, $81, $79, $8a, $2d, $95, $78, $83, $77, $83, $76, $83, $75, $83, $7c, $4f, $01, $88, $29
	.byte $8d, $7a, $29, $81, $78, $8a, $24, $76, $81, $79, $86, $29, $77, $81, $7b, $30, $99, $7a, $88, $30, $81, $79, $86, $32
	.byte $76, $81, $7b, $33, $91, $88, $33, $35, $83, $79, $8a, $33, $81, $7a, $32, $85, $79, $88, $30, $85, $78, $8a, $2e, $85
	.byte $7a, $88, $2b, $81, $77, $86, $29, $74, $81, $7a, $2d, $85, $79, $88, $2d, $81, $78, $86, $2e, $75, $81, $7b, $30, $8d
	.byte $7a, $83, $79, $83, $78, $83, $77, $83, $76, $87, $75, $8f, $7a, $88, $35, $81, $79, $86, $37, $76, $81, $7b, $39
@song0ref1396:
	.byte $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $83, $7b, $3a, $85, $7a, $87
	.byte $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $8b, $7a, $8a, $38, $81, $79, $86, $37, $74
	.byte $81, $7b, $8a, $35, $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $83, $79
	.byte $33, $81, $7a, $86, $35, $81, $79, $37, $81, $7a, $8a, $33, $76, $81, $7a, $86, $35, $81, $73, $83, $7b, $8a, $2e, $88
	.byte $30, $83, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $93, $79, $8a, $2b, $81
	.byte $7a, $86, $2c, $81, $7b, $2e, $81, $74, $83, $7b, $8a, $2c, $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75
	.byte $83, $74, $83, $7b, $86, $30, $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72
	.byte $8b, $7a, $31, $81, $79, $33, $76, $81, $7b, $35, $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74
	.byte $83, $73, $83, $72, $83, $77, $37, $81, $78, $88, $38, $81, $79, $86, $3a, $81, $7a, $8a, $37, $76, $81, $7a, $86, $38
	.byte $81, $73, $83, $7b, $8a, $35, $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $77, $2e, $81
	.byte $78, $86, $30, $81, $79, $33, $81, $7a, $8a, $30, $76, $81, $7a, $86, $35, $81, $73, $83, $7b, $8a, $30
@song0ref1657:
	.byte $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $85, $73, $87, $72, $85, $7a
@song0ref1677:
	.byte $92, $1b, $8d, $7b, $1b, $8d, $1b, $89, $94, $1b, $81, $7a, $1b, $81, $47, $01, $7b, $1b, $83, $47, $00, $7c, $1b, $83
	.byte $98, $1b, $8d, $7b, $1b, $8d, $1b, $89, $7a, $9a, $1b, $81, $1b, $81, $47, $01, $7b, $1b, $83, $47, $00, $7a, $1b, $83
	.byte $41, $1c
	.word @song0ref1677
	.byte $41, $1c
	.word @song0ref1677
	.byte $41, $1c
	.word @song0ref1677
	.byte $7d, $4f, $02, $88, $2c, $8d, $7a, $2c, $81, $78, $8a, $27, $74, $81, $7a, $86, $2e, $77, $81, $7b, $30, $97, $71, $81
	.byte $77, $88, $30, $81, $78, $86, $31, $74, $81, $7c, $33, $91, $7a, $88, $33, $35, $83, $7b, $8a, $33, $79, $81, $7c, $31
	.byte $83, $7a, $81, $79, $88, $30, $85, $7a, $8a, $2e, $85, $77, $88, $2c, $81, $78, $86, $2e, $76, $81, $7c, $4f, $02, $30
	.byte $81, $7b, $81, $78, $81, $7a, $88, $30, $81, $79, $86, $31, $76, $81, $7a, $33, $95, $79, $87, $78, $87, $77, $87, $76
	.byte $83, $75, $83, $77, $88, $2c, $81, $78, $86, $2e, $81, $79, $88, $30, $81, $7a, $31, $76, $81, $79, $8a, $30, $95, $78
	.byte $83, $77, $83, $76, $83, $75, $83, $7c, $4f, $01, $88, $2c, $8d, $7a, $2c, $81, $78, $8a, $27, $76, $81, $79, $86, $2c
	.byte $77, $81, $7b, $33, $99, $7a, $88, $33, $81, $79, $86, $35, $76, $81, $7b, $36, $91, $88, $36, $38, $83, $79, $8a, $36
	.byte $81, $7a, $35, $85, $79, $88, $33, $85, $78, $8a, $31, $85, $7a, $88, $2e, $81, $77, $86, $2c, $74, $81, $7a, $30, $85
	.byte $79, $88, $30, $81, $78, $86, $31, $75, $81, $7b, $33, $8d, $7a, $83, $79, $83, $78, $83, $77, $83, $76, $87, $75, $8f
	.byte $7a, $88, $38, $81, $79, $86, $3a, $76, $81, $7b, $3c
	.byte $41, $17
	.word @song0ref1396
	.byte $79, $37, $74, $81, $7b, $86, $38, $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83
	.byte $72, $83, $79, $8a, $35, $81, $7a, $86, $37, $81, $79, $38, $81, $7a, $8a, $37, $76, $81, $7a, $35, $81, $73, $83, $7b
	.byte $86, $3a, $88, $3c, $83, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83, $73, $83, $72, $93, $79
	.byte $8a, $33, $81, $7a, $86, $35, $81, $7b, $37, $81, $74, $83, $7b, $8a, $35, $85, $7a, $87, $79, $83, $78, $83, $77, $83
	.byte $76, $83, $75, $83, $74, $83, $7b, $86, $38, $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74, $83
	.byte $73, $83, $72, $8b, $7a, $8a, $37, $81, $79, $86, $38, $76, $81, $7b, $3a, $85, $7a, $87, $79, $83, $78, $83, $77, $83
	.byte $76, $83, $75, $83, $74, $83, $73, $83, $72, $83, $77, $8a, $38, $81, $78, $88, $3a, $81, $79, $86, $3c, $81, $7a, $3d
	.byte $76, $81, $7a, $8a, $3c, $81, $73, $83, $7b, $38, $85, $7a, $87, $79, $83, $78, $83, $77, $83, $76, $83, $75, $83, $74
	.byte $83, $77, $35, $81, $78, $86, $37, $81, $79, $38, $81, $7a, $3a, $76, $81, $7a, $8a, $38, $81, $73, $83, $7b, $35
	.byte $41, $26
	.word @song0ref1657
	.byte $41, $1c
	.word @song0ref1677
@song0ref2185:
	.byte $ae, $1b, $8d, $7b, $1b, $8d, $1b, $89, $a6, $1b, $81, $7a, $1b, $81, $47, $01, $7b, $1b, $83, $47, $00, $7c, $1b, $83
	.byte $a8, $1b, $8d, $7b, $1b, $8d, $1b, $89, $7a, $aa, $1b, $81, $1b, $81, $47, $01, $7b, $1b, $83, $47, $00, $7a, $1b, $83
	.byte $41, $1c
	.word @song0ref2185
	.byte $7c, $b0, $24, $b9, $78, $29, $81, $7a, $2b, $ad, $78, $2e, $8d, $79, $2d, $85, $7a, $29, $85, $7b, $24, $85, $79, $22
	.byte $8d, $78, $21, $8d, $79, $29, $c5, $7c, $2b, $b5, $77, $2d, $81, $78, $2e, $81, $7a, $30, $ad, $79, $35, $8d, $78, $37
	.byte $85, $79, $35, $85, $7b, $30, $85, $79, $2e, $8d, $78, $2d, $8d, $7a, $35, $c5, $7c, $2c, $9d, $7a, $2b, $99, $78, $2c
	.byte $77, $2b, $7a, $29, $9d, $79, $29, $85, $78, $2b, $85, $79, $2c, $85, $7a, $2e, $85, $7b, $30, $ad, $79, $35, $85, $77
	.byte $37, $85, $76, $38, $8d, $77, $37, $85, $79, $35, $8d, $78, $30, $95, $7c, $2e, $9d, $79, $2c, $99, $78, $2e, $77, $2c
	.byte $7a, $2b, $9d, $79, $2c, $85, $78, $2e, $85, $7a, $30, $85, $7b, $31, $85, $7a, $30, $ad, $78, $38, $85, $77, $3a, $85
	.byte $78, $3c, $b5, $7d, $4f, $02, $88, $18, $85, $1d, $85, $7c, $87, $7d, $1d, $81, $18, $74, $81, $7d, $1f, $74, $81, $7d
	.byte $20, $85, $7c, $87, $7b, $87, $79, $83, $7d, $20, $81, $22, $74, $81, $7d, $22, $24, $83, $22, $74, $81, $7d, $20, $85
	.byte $7c, $87, $7b, $83, $7a, $83, $79, $83, $78, $83, $77, $83, $76, $85, $75, $87, $74, $81, $7d, $4f, $01, $20, $85, $7c
	.byte $87, $7d, $20, $81, $1d, $74, $81, $7d, $20, $74, $81, $7d, $22, $85, $7c, $87, $7b, $87, $79, $83, $7d, $24, $81, $25
	.byte $81, $27, $85, $25, $74, $81, $7d, $24, $85, $7c, $87, $7b, $83, $7a, $83, $79, $83, $78, $83, $77, $83, $76, $85, $75
	.byte $87, $74, $81, $7d, $4f, $02, $24
@song0ref2507:
	.byte $85, $7c, $87, $7d, $29, $81, $24, $74, $81, $7d, $2b, $74, $81, $7d, $2c, $85, $7c, $87, $7b, $87, $79, $83, $7d, $2c
	.byte $81, $2e, $74, $81, $7d, $2e, $30, $83, $2e, $74, $81, $7d, $2c, $85, $7c, $87, $7b, $83, $7a, $83, $79, $83, $78, $83
	.byte $77, $83, $76, $85, $75, $87, $74, $81, $7d, $4f, $01, $29
	.byte $41, $14
	.word @song0ref2507
	.byte $7c, $87, $7b, $83, $7a, $83, $79, $83, $78, $83, $77, $83, $76, $85, $75, $85, $74, $83, $73, $83, $7a, $2d, $81, $7b
	.byte $2e, $81, $7c, $30, $85, $7b, $83, $7a, $83, $79, $83, $78, $83, $77, $83, $76, $85, $75, $85, $74, $83, $73, $83, $72
	.byte $83, $71, $83, $87, $79, $82
	.byte $41, $20
	.word @song0ref1044
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $00, $fd
@song0ch2loop:
	.byte $00, $fd, $ff, $ff, $b2
@song0ref2638:
	.byte $11, $91, $00, $81, $0c, $a5, $00, $85, $0f, $89, $00, $81, $0a, $9d, $00, $85
	.byte $41, $10
	.word @song0ref2638
	.byte $41, $10
	.word @song0ref2638
	.byte $41, $10
	.word @song0ref2638
	.byte $0d, $91, $00, $81, $14, $a5, $00, $85, $08, $89, $00, $81, $0d
@song0ref2676:
	.byte $95, $0d, $85, $00, $85, $11, $91, $00, $81, $0c, $a5, $00, $85, $0f, $89, $00, $81
@song0ref2693:
	.byte $11, $95, $11
@song0ref2696:
	.byte $85
@song0ref2697:
	.byte $00, $85, $0d, $91, $00, $81, $14, $a5, $00, $85, $08, $89, $00, $81, $0d, $91, $00, $81, $0c, $89, $00, $81
@song0ref2719:
	.byte $11, $91, $00, $81, $11, $a5, $00, $85, $0f, $89, $00, $81, $11, $95, $11
@song0ref2734:
	.byte $85
@song0ref2735:
	.byte $00, $85, $11, $91, $00, $81, $18, $a5, $00, $85, $0f, $89, $00, $81, $16, $95, $16
	.byte $41, $12
	.word @song0ref2734
	.byte $41, $12
	.word @song0ref2734
	.byte $41, $12
	.word @song0ref2734
@song0ref2761:
	.byte $85, $00, $85, $14, $91, $00, $81, $0f, $a5, $00, $85, $12, $89, $00, $81, $0d, $95, $0d
	.byte $41, $12
	.word @song0ref2761
	.byte $41, $12
	.word @song0ref2761
	.byte $41, $12
	.word @song0ref2761
	.byte $41, $10
	.word @song0ref2696
	.byte $41, $4c
	.word @song0ref2676
	.byte $41, $12
	.word @song0ref2734
	.byte $41, $12
	.word @song0ref2734
	.byte $41, $12
	.word @song0ref2734
	.byte $41, $10
	.word @song0ref2734
	.byte $9d
	.byte $41, $0f
	.word @song0ref2735
	.byte $9d
	.byte $41, $0f
	.word @song0ref2735
	.byte $9d
	.byte $41, $0f
	.word @song0ref2735
	.byte $9d
	.byte $41, $0f
	.word @song0ref2697
	.byte $95, $0c
	.byte $41, $0f
	.word @song0ref2734
	.byte $41, $13
	.word @song0ref2693
	.byte $95, $0c, $85, $00, $85
	.byte $41, $13
	.word @song0ref2719
@song0ref2838:
	.byte $89
@song0ref2839:
	.byte $00, $81, $11, $85, $11, $81, $00, $81, $11, $87, $00, $11, $47, $00, $00, $11, $47, $01, $00, $47, $01, $11, $81, $47
	.byte $00, $00, $47, $00, $11, $81, $00, $11, $85, $11, $81
	.byte $41, $16
	.word @song0ref2839
	.byte $41, $1a
	.word @song0ref2838
	.byte $41, $16
	.word @song0ref2839
	.byte $41, $1a
	.word @song0ref2838
	.byte $41, $16
	.word @song0ref2839
	.byte $41, $1a
	.word @song0ref2838
	.byte $41, $15
	.word @song0ref2839
	.byte $ff, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff
@song0ch3loop:
	.byte $87
@song0ref2902:
	.byte $78
@song0ref2903:
	.byte $80
@song0ref2904:
	.byte $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $89, $78
	.byte $41, $0f
	.word @song0ref2904
	.byte $81, $78, $90, $21, $85
	.byte $41, $10
	.word @song0ref2903
	.byte $78
	.byte $41, $0f
	.word @song0ref2904
	.byte $81, $78, $90, $21, $85
	.byte $41, $10
	.word @song0ref2903
@song0ref2951:
	.byte $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $81, $7b, $96, $1d, $8d, $7a, $8e
	.byte $1d, $95
	.byte $41, $10
	.word @song0ref2902
@song0ref2980:
	.byte $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $81, $78, $90, $21, $85
	.byte $41, $10
	.word @song0ref2903
	.byte $78
	.byte $41, $0f
	.word @song0ref2904
	.byte $81, $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $0e
	.word @song0ref2980
	.byte $41, $10
	.word @song0ref2903
	.byte $41, $10
	.word @song0ref2951
	.byte $41, $10
	.word @song0ref2902
@song0ref3029:
	.byte $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $81, $7f, $8c, $14, $85, $78, $80, $1e, $81, $76, $1e, $81, $78
	.byte $90, $21, $85
	.byte $41, $10
	.word @song0ref2903
	.byte $78, $1e, $81, $76, $1e, $89
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
@song0ref3081:
	.byte $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $81, $7f, $8c, $14, $81, $7b, $96
	.byte $1d, $89, $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $78, $1e, $81, $76, $1e, $89
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $41, $12
	.word @song0ref3081
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $78, $1e, $81, $76, $1e, $89
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $41, $12
	.word @song0ref3081
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $78, $1e, $81, $76, $1e, $89
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $41, $12
	.word @song0ref3081
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $78, $1e, $81, $76, $1e, $89
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $41, $12
	.word @song0ref3081
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $0e
	.word @song0ref2980
	.byte $41, $10
	.word @song0ref2903
	.byte $78
	.byte $41, $0f
	.word @song0ref2904
	.byte $81, $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $0e
	.word @song0ref2980
	.byte $41, $10
	.word @song0ref2903
	.byte $41, $10
	.word @song0ref2951
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $78, $1e, $81, $76, $1e, $89
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $10
	.word @song0ref3029
	.byte $41, $10
	.word @song0ref2903
	.byte $41, $12
	.word @song0ref3081
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $41, $0e
	.word @song0ref3029
	.byte $7a, $8e, $1d, $95
	.byte $41, $10
	.word @song0ref2902
	.byte $78, $1e, $81, $76, $1e, $89, $78, $1e, $81, $76, $1e, $81, $7f, $8c, $14, $81, $7b, $96, $1d, $89, $7a, $8e, $1d, $9d
	.byte $00, $dd, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff
@song0ch4loop:
	.byte $ff
@song0ref3376:
	.byte $01, $95, $01, $ad, $01, $8d, $01, $a5, $01, $95, $01, $ad, $01, $8d, $01, $a5
	.byte $41, $10
	.word @song0ref3376
	.byte $41, $10
	.word @song0ref3376
@song0ref3398:
	.byte $01, $95, $01, $ad, $01, $8d, $01, $95, $02, $8d, $01, $95, $01, $ad, $01, $8d, $01, $95, $02, $8d
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $10
	.word @song0ref3376
	.byte $41, $10
	.word @song0ref3376
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $41, $14
	.word @song0ref3398
	.byte $ff, $42
	.word @song0ch4loop
